//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string PARENT { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> BAL { get; set; }
        public Nullable<System.DateTime> BALDATE { get; set; }
        public Nullable<decimal> BAL1 { get; set; }
        public Nullable<System.DateTime> BALDATE1 { get; set; }
        public int NORMAL { get; set; }
        public decimal DR { get; set; }
        public decimal CR { get; set; }
        public decimal YDR { get; set; }
        public decimal YCR { get; set; }
        public int ISCASH { get; set; }
        public int ISBANK { get; set; }
        public int CHILDS { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> ISINPUTVAT { get; set; }
        public Nullable<int> ISOUTPUTVAT { get; set; }
        public Nullable<int> ISTEMPRECACC { get; set; }
        public Nullable<int> ISTEMPPAYACC { get; set; }
    }
}
