//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCRPT
    {
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public int RPTTYPE { get; set; }
        public int LVL { get; set; }
        public int ORD { get; set; }
        public int COUNTER { get; set; }
        public int SROW { get; set; }
        public int SCOL { get; set; }
        public int PERIODFROM { get; set; }
        public int PERIODTO { get; set; }
        public int USEDOCDATE { get; set; }
        public int USEOBAL { get; set; }
        public int SHOWNOENTRY { get; set; }
        public System.DateTime DATEFROM { get; set; }
        public System.DateTime DATETO { get; set; }
        public string JOUFROM { get; set; }
        public string JOUTO { get; set; }
    }
}
