//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APAYDTL
    {
        public string APNUM { get; set; }
        public string BASETYPE { get; set; }
        public string BASENUM { get; set; }
        public Nullable<System.DateTime> BASEDATE { get; set; }
        public string DOCNUM { get; set; }
        public decimal ORIAMT { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public decimal BASEAMT { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
    }
}
