//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APREQA
    {
        public string AQNUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string VENID { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public string INVTYPE { get; set; }
        public decimal TAXRATE { get; set; }
        public decimal AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
    }
}
