//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class APREQB
    {
        public string AQNUM { get; set; }
        public string BASETYPE { get; set; }
        public string DOCNUM { get; set; }
        public string ODNUM { get; set; }
        public System.DateTime DOCDATE { get; set; }
        public decimal AMOUNT { get; set; }
        public string REMARKS { get; set; }
    }
}
