//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARECDC
    {
        public string ARNUM { get; set; }
        public int LINEID { get; set; }
        public string ACCNUM { get; set; }
        public string LINEMEMO { get; set; }
        public decimal DEBIT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
    }
}
