//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREC
    {
        public string ARNUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string CUSID { get; set; }
        public string RECACC { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public string CHK { get; set; }
        public string CHKACC { get; set; }
        public string PAYMETHOD { get; set; }
        public decimal ORIAMT { get; set; }
        public decimal BASEAMT { get; set; }
        public int DEPOSIT { get; set; }
        public string SONUM { get; set; }
        public string PRJNUM { get; set; }
        public string REMARK { get; set; }
        public int POST { get; set; }
        public Nullable<int> VNUM { get; set; }
        public string DEPTID { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
