//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMDTL
    {
        public string ANCESTOR { get; set; }
        public string ITEMNUM { get; set; }
        public int SEQNUM { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public decimal SCPRATE { get; set; }
        public int ISKEY { get; set; }
        public int ISREP { get; set; }
        public string MASTERITEMNUM { get; set; }
        public string REMARK { get; set; }
        public string EXTRA1 { get; set; }
        public string EXTRA2 { get; set; }
        public Nullable<decimal> REPRATE { get; set; }
    }
}
