//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKMARK
    {
        public string MID { get; set; }
        public string TYPE { get; set; }
        public string PREFIX { get; set; }
        public string CY { get; set; }
        public string CM { get; set; }
        public Nullable<int> CURNUM { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public Nullable<int> DENYINPUT { get; set; }
    }
}
