//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTNMNU
    {
        public string MID { get; set; }
        public int ITEMID { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMDESCR { get; set; }
        public string ITEMTYPE { get; set; }
        public string ITEMACTION { get; set; }
        public string ITEMREPORTNAME { get; set; }
        public string ITEMSCRIPT { get; set; }
    }
}
