//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMINF
    {
        public string COMPNAMECHN { get; set; }
        public string COMPNAMEENG { get; set; }
        public string CURR { get; set; }
        public string ADDRCHN { get; set; }
        public string ADDRENG { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string WEBSITE { get; set; }
        public string EMAIL { get; set; }
        public string MASTER { get; set; }
        public string SINSUREACC { get; set; }
        public string SHANDLEACC { get; set; }
        public string PINSUREACC { get; set; }
        public string PHANDLEACC { get; set; }
        public string SALESTAXACC { get; set; }
        public string PURTAXACC { get; set; }
        public string TRANSACC { get; set; }
        public Nullable<int> STARTYEAR { get; set; }
        public Nullable<int> STARTPERIOD { get; set; }
        public Nullable<int> ACTYEAR { get; set; }
        public Nullable<int> ACTPERIOD { get; set; }
        public Nullable<int> DECIMALS { get; set; }
        public Nullable<int> STARTUP { get; set; }
        public string PCONTACT { get; set; }
        public string PEMAIL { get; set; }
        public string PTEL { get; set; }
        public string PFAX { get; set; }
        public string SCONTACT { get; set; }
        public string SEMAIL { get; set; }
        public string STEL { get; set; }
        public string SFAX { get; set; }
        public string WCONTACT { get; set; }
        public string WEMAIL { get; set; }
        public string WTEL { get; set; }
        public string WFAX { get; set; }
        public string WADDRESS { get; set; }
        public string LICENSECODE { get; set; }
        public Nullable<int> LICENSEUSER { get; set; }
        public string VERCODE { get; set; }
        public string REPORTSPATH { get; set; }
        public string LOGOPATH { get; set; }
        public Nullable<System.DateTime> EXPIRED { get; set; }
    }
}
