//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRAPLY
    {
        public string CANUM { get; set; }
        public string CUSID { get; set; }
        public System.DateTime IDATE { get; set; }
        public Nullable<decimal> OUTSOAMT { get; set; }
        public Nullable<decimal> CLBAL { get; set; }
        public Nullable<decimal> CRDLIMIT { get; set; }
        public Nullable<decimal> OLDXLIMIT { get; set; }
        public Nullable<System.DateTime> OLDXDATE { get; set; }
        public decimal NEWXLIMIT { get; set; }
        public System.DateTime NEWXDATE { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public int STATUS { get; set; }
        public Nullable<decimal> NEWCREDITLIMIT { get; set; }
        public Nullable<int> ISCRLMT { get; set; }
        public Nullable<int> ISCRLMTSO { get; set; }
    }
}
