//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSTCPA
    {
        public int FPERIOD { get; set; }
        public string WOTYPE { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string PARTNUM { get; set; }
        public string MASTERITEMNUM { get; set; }
        public string MITYPE { get; set; }
        public Nullable<System.DateTime> MIDATE { get; set; }
        public string REFPONUM { get; set; }
        public string REFWONUM { get; set; }
        public string LOCID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> ISREWORK { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> ISREP { get; set; }
        public Nullable<decimal> REPRATE { get; set; }
        public Nullable<decimal> DOSAGE { get; set; }
        public int ISUNLIMITED { get; set; }
    }
}
