//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSTPAM
    {
        public int CSTPAM1 { get; set; }
        public Nullable<int> CALCBTNDISPLAY { get; set; }
        public string MATERIALITEMGRP { get; set; }
        public string PRODUCTITEMGRP { get; set; }
        public string FIXEDASSETSITEMGRP { get; set; }
        public Nullable<int> INITPERIOD { get; set; }
    }
}
