//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSEVA
    {
        public string CENUM { get; set; }
        public string CUSID { get; set; }
        public string CUSNAME { get; set; }
        public string SHORTNAME { get; set; }
        public string CUSTYPE { get; set; }
        public string CURR { get; set; }
        public string INVTYPE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string SALESREGION { get; set; }
        public string SALESREP { get; set; }
        public Nullable<decimal> CREDITLIMIT { get; set; }
        public Nullable<int> ISCRLMT { get; set; }
        public Nullable<decimal> REGISTERCAPITAL { get; set; }
        public Nullable<System.DateTime> REGISTERDATE { get; set; }
        public Nullable<decimal> VALIDPERIOD { get; set; }
        public string BUSINESSSCOPE { get; set; }
        public string LEGALMASTER { get; set; }
        public string PURCONTACT { get; set; }
        public string PURMAIL { get; set; }
        public string PURTEL { get; set; }
        public string PURFAX { get; set; }
        public string PURADDR { get; set; }
        public string SHIPTOCONTACT { get; set; }
        public string SHIPTOMAIL { get; set; }
        public string SHIPTOTEL { get; set; }
        public string SHIPTOFAX { get; set; }
        public string SHIPTOADDR { get; set; }
        public string BILLTOCONTACT { get; set; }
        public string BILLTOMAIL { get; set; }
        public string BILLTOTEL { get; set; }
        public string BILLTOFAX { get; set; }
        public string BILLTOADDR { get; set; }
        public string RECACC { get; set; }
        public string SALESACC { get; set; }
        public string ARACC { get; set; }
        public string RECTMPACC { get; set; }
        public string ORACC { get; set; }
        public string INVOUTACC { get; set; }
        public int ISCONFIRMED { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string RANKLEVEL { get; set; }
    }
}
