//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICTAB
    {
        public int DICTID { get; set; }
        public int DICTFIELDID { get; set; }
        public string DICTFIELD { get; set; }
        public string DICTFIELDNAME { get; set; }
        public string DICTFIELDTYPE { get; set; }
        public string CTLTYPE { get; set; }
        public string DATASRC { get; set; }
        public string DATAVALUE { get; set; }
        public string DATATEXT { get; set; }
    }
}
