//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECNBOM
    {
        public string ANCESTOR { get; set; }
        public string ECNNUM { get; set; }
        public string DOCNUM { get; set; }
        public Nullable<System.DateTime> RELEASEDATE { get; set; }
        public string REV { get; set; }
        public string REMARK { get; set; }
        public string ADDONS { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public int RELEASED { get; set; }
        public string ECNBOMNUM { get; set; }
        public string WORKPROC { get; set; }
    }
}
