//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECNTEB
    {
        public string ECNTENUM { get; set; }
        public int SEQNUM { get; set; }
        public string ANCESTOR { get; set; }
        public string PARTNUM1 { get; set; }
        public string UOM1 { get; set; }
        public Nullable<decimal> QTY1 { get; set; }
        public Nullable<decimal> SCPRATE1 { get; set; }
        public string PARTNUM2 { get; set; }
        public string UOM2 { get; set; }
        public Nullable<decimal> QTY2 { get; set; }
        public Nullable<decimal> SCPRATE2 { get; set; }
        public string REMARKS { get; set; }
    }
}
