//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFILEC
    {
        public long FOLDERID { get; set; }
        public string FOLDERNAME { get; set; }
        public long PARENTID { get; set; }
        public Nullable<bool> ISSHARE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
