//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFILEB
    {
        public string TYPEID { get; set; }
        public string MID { get; set; }
        public string NAME { get; set; }
        public int CANVIEW { get; set; }
        public int CANVIEWALL { get; set; }
        public int CANUPLOAD { get; set; }
        public int CANDELETE { get; set; }
    }
}
