//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EINBOX
    {
        public int NID { get; set; }
        public string RECIPIENT { get; set; }
        public string FOLDER { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public Nullable<int> OPENED { get; set; }
        public Nullable<int> WASREAD { get; set; }
        public Nullable<int> DELETED { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ISNEWMAIL { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
    }
}
