//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENOTE
    {
        public int NID { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string SENDBY { get; set; }
        public string RECIPIENTS { get; set; }
        public string COPYRECIPIENTS { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public string DATAPARAMS { get; set; }
        public string MSGDATA { get; set; }
        public string ATTACHMENT { get; set; }
        public Nullable<int> WASSENT { get; set; }
        public Nullable<System.DateTime> SENDSTAMP { get; set; }
    }
}
