//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPCOT
    {
        public int FPERIOD { get; set; }
        public string PROLINE { get; set; }
        public decimal COST1 { get; set; }
        public decimal COST2 { get; set; }
        public decimal COST3 { get; set; }
    }
}
