//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string FIELD { get; set; }
        public string DATATYPE { get; set; }
        public string FIELDNAME { get; set; }
        public string DEFAULTVALUE { get; set; }
        public string FORMAT { get; set; }
        public int ORDER { get; set; }
        public string GROUP1 { get; set; }
        public Nullable<int> GROUP1ORD { get; set; }
        public string GROUP2 { get; set; }
        public Nullable<int> GROUP2ORD { get; set; }
    }
}
