//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACDAR
    {
        public string PROLINEID { get; set; }
        public System.DateTime FACDATE { get; set; }
        public Nullable<decimal> WORKHOUR { get; set; }
        public string REMARK { get; set; }
    }
}
