//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLWDAT
    {
        public int FDID { get; set; }
        public Nullable<int> WFID { get; set; }
        public string USRID { get; set; }
        public string DOCENTRY { get; set; }
        public string OBJTYPE { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public Nullable<int> CURRSTEP { get; set; }
        public string FSTATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string ISDRAFT { get; set; }
    }
}
