//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLWDAD
    {
        public int FDID { get; set; }
        public int STPID { get; set; }
        public string USRID { get; set; }
        public string FSTATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
        public string STPNAME { get; set; }
        public Nullable<int> SORTID { get; set; }
        public Nullable<int> ALLOWPRINT { get; set; }
        public Nullable<int> TOBEEND { get; set; }
        public Nullable<int> FLWRULE { get; set; }
        public Nullable<int> WFID { get; set; }
        public Nullable<int> WAITING { get; set; }
        public string AGENTUID { get; set; }
        public string APPROVALBY { get; set; }
        public Nullable<int> MAILNOTIFY { get; set; }
    }
}
