//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOMLAB
    {
        public int ID { get; set; }
        public string TYPEID { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public string DATASRC { get; set; }
        public string SELECTFIELD { get; set; }
        public string FILTERFIELD { get; set; }
        public string INPUTFIELD { get; set; }
    }
}
