//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPERIOD
    {
        public int CODE { get; set; }
        public System.DateTime BEGDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public System.DateTime F_DUEDATE { get; set; }
        public System.DateTime T_DUEDATE { get; set; }
        public int ACTIVED { get; set; }
        public int LOCKED { get; set; }
        public int SUBYEAR { get; set; }
        public int SUBMONTH { get; set; }
        public int PERIODNUM { get; set; }
    }
}
