//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRACRC
    {
        public int GRACRC_ID { get; set; }
        public int GRACRB_ID { get; set; }
        public int GRACRA_ID { get; set; }
        public string RANKSTDDTL_CODE { get; set; }
        public Nullable<decimal> MIN { get; set; }
        public Nullable<decimal> MAX { get; set; }
        public string RANGEUOM { get; set; }
        public Nullable<decimal> X1 { get; set; }
        public Nullable<decimal> Y1 { get; set; }
        public Nullable<decimal> X2 { get; set; }
        public Nullable<decimal> Y2 { get; set; }
        public Nullable<decimal> X3 { get; set; }
        public Nullable<decimal> Y3 { get; set; }
        public Nullable<decimal> X4 { get; set; }
        public Nullable<decimal> Y4 { get; set; }
        public int SEQNUM { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
