//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAMPB
    {
        public int GRAMPB_ID { get; set; }
        public int GRAMPA_ID { get; set; }
        public Nullable<int> COORAA_ID { get; set; }
        public string DATATYPE { get; set; }
        public string SHOWNAME { get; set; }
        public string UOM { get; set; }
        public string FONTCOLOUR { get; set; }
        public int SEQNUM { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
