//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQC
    {
        public string IQCNUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string DOCNUM { get; set; }
        public string INSPECTOR { get; set; }
        public string GRNNUM { get; set; }
        public string PONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public decimal CHECKQTY { get; set; }
        public decimal SAMPLEQTY { get; set; }
        public decimal DEFECTQTY { get; set; }
        public string DEFECTHANDLING { get; set; }
        public string HANDLING { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
        public string SINUM { get; set; }
        public Nullable<decimal> SIQTY { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
    }
}
