//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMPM
    {
        public string TYPECODE { get; set; }
        public int PARAMCODE { get; set; }
        public string PARAMDESCR { get; set; }
        public int PARAMORD { get; set; }
        public int ALLOWNULL { get; set; }
    }
}
