//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMSP
    {
        public string ITEMNUM { get; set; }
        public string SYSTYPE { get; set; }
        public int SEQNUM { get; set; }
        public decimal QTY1 { get; set; }
        public decimal QTY2 { get; set; }
        public decimal UPRICE1 { get; set; }
        public decimal UPRICE2 { get; set; }
        public string LASTAPPNUM { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string CUSVEN { get; set; }
        public string CURR { get; set; }
    }
}
