//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMTYPE
    {
        public string CODE { get; set; }
        public string DESCR { get; set; }
        public string PARENTID { get; set; }
        public Nullable<int> MINLEN { get; set; }
        public Nullable<int> MAXLEN { get; set; }
        public string ATTRIBTYPE { get; set; }
        public string INVACC { get; set; }
        public Nullable<decimal> OVERQTY { get; set; }
        public Nullable<int> ISFGREF { get; set; }
        public string ITEMGRP { get; set; }
        public Nullable<int> ISVIRTUAL { get; set; }
        public Nullable<int> LOTMANAGED { get; set; }
        public Nullable<decimal> OVERRATE { get; set; }
        public string PREFIX { get; set; }
    }
}
