//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public string ITEMNUM { get; set; }
        public string ITEMDESCR { get; set; }
        public string ITEMDESCRENG { get; set; }
        public string SPEC { get; set; }
        public string SPECCHN { get; set; }
        public string SPECENG { get; set; }
        public string DRAWNUM { get; set; }
        public string ECNNUM { get; set; }
        public string UOM { get; set; }
        public Nullable<int> LEADTIME { get; set; }
        public Nullable<decimal> SAFETYSTOCK { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public string ITEMTYPE { get; set; }
        public string BRAND { get; set; }
        public string SRCTYPE { get; set; }
        public Nullable<decimal> MAXORDQTY { get; set; }
        public Nullable<decimal> MINORDQTY { get; set; }
        public Nullable<decimal> FIXORDQTY { get; set; }
        public Nullable<decimal> ECONLOTSIZE { get; set; }
        public Nullable<decimal> REORDQTY { get; set; }
        public string BATCHPRINC { get; set; }
        public string ORDPOLICY { get; set; }
        public string ABC { get; set; }
        public Nullable<decimal> YIELD { get; set; }
        public string INSPECGRADE { get; set; }
        public Nullable<int> SAMPLES { get; set; }
        public string INSPECDESCR { get; set; }
        public string INSPECLEVEL { get; set; }
        public string SAMPLESSTD { get; set; }
        public string AQL { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> GROSSWEIGHT { get; set; }
        public Nullable<decimal> NETWEIGHT { get; set; }
        public Nullable<int> GUAPERIOD { get; set; }
        public string EXUOM { get; set; }
        public Nullable<decimal> EXRATE { get; set; }
        public string COLOR { get; set; }
        public string ANGLE { get; set; }
        public Nullable<int> ISBACKFLUSH { get; set; }
        public string VENDOR { get; set; }
        public string CITEMNUM { get; set; }
        public string VITEMNUM { get; set; }
        public Nullable<decimal> COST1 { get; set; }
        public Nullable<decimal> LASTPOUPRICE { get; set; }
        public string LASTPONUM { get; set; }
        public Nullable<System.DateTime> LASTPODATE { get; set; }
        public Nullable<decimal> LASTSOUPRICE { get; set; }
        public string LASTSONUM { get; set; }
        public Nullable<System.DateTime> LASTSODATE { get; set; }
        public Nullable<int> ALLOWOVERORDER { get; set; }
        public Nullable<decimal> MINPACKQTY { get; set; }
        public Nullable<int> ISDENY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> DENYSTAMP { get; set; }
        public string DENYUSER { get; set; }
        public Nullable<decimal> REFUPRICE { get; set; }
        public string REFUOM { get; set; }
        public Nullable<int> ISSUBCON { get; set; }
        public string STYLE { get; set; }
        public string STYLETYPE { get; set; }
        public Nullable<int> CHIPCOUNT { get; set; }
    
        public virtual ITEMGRP ITEMGRP { get; set; }
    }
}
