//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPDATA
    {
        public int ID { get; set; }
        public string ITEMNUM { get; set; }
        public string DEEPTH { get; set; }
        public string SURFACE { get; set; }
        public string MODSPACING { get; set; }
        public decimal LUX { get; set; }
        public decimal MODQTY { get; set; }
        public decimal CAPACITY { get; set; }
        public string REMARKS { get; set; }
    }
}
