//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATINA
    {
        public int FPERIOD { get; set; }
        public string DOCNUM { get; set; }
        public string PONUM { get; set; }
        public string VENID { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> NONETAXUPRICE { get; set; }
        public Nullable<decimal> NONETAXAMOUNT { get; set; }
        public string REMARK { get; set; }
        public string DTYPE { get; set; }
        public string SCITEMNUM { get; set; }
        public Nullable<decimal> SCUPRICE { get; set; }
        public Nullable<int> ISCHECKED { get; set; }
        public Nullable<System.DateTime> CHECKEDSTAMP { get; set; }
        public string CHECKEDUSER { get; set; }
        public Nullable<int> POST { get; set; }
        public string VNUM { get; set; }
        public string INVNUM { get; set; }
        public string AQNUM { get; set; }
        public string WFSTATUS { get; set; }
        public Nullable<decimal> SCRAPQTY { get; set; }
    }
}
