//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESRFA
    {
        public string MESRFNUM { get; set; }
        public System.DateTime MESRFDATE { get; set; }
        public string MESRFTYPE { get; set; }
        public string LOCID { get; set; }
        public string ORIDOCNUM { get; set; }
        public decimal TOTALQTY { get; set; }
        public string REMARKS { get; set; }
        public int COMPLETED { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
    }
}
