//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESTPA
    {
        public string MESTPNUM { get; set; }
        public System.DateTime MESTPDATE { get; set; }
        public string WONUM { get; set; }
        public string PRODUCTIONLINE { get; set; }
        public string LABELID { get; set; }
        public string DEVNUM { get; set; }
        public decimal TOTALINPUTQTY { get; set; }
        public decimal TOTALOUTPUTQTY { get; set; }
        public string REMARKS { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
