//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESWOC
    {
        public string WONUM { get; set; }
        public int SEQNUM { get; set; }
        public string DEVNUM { get; set; }
        public string BINNUM { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public string SERIESNUM { get; set; }
        public Nullable<int> PRINTCNT { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
