//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESWOA
    {
        public string WONUM { get; set; }
        public System.DateTime WODATE { get; set; }
        public string WOTYPE { get; set; }
        public string WOTYPE2 { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string ECNNUM { get; set; }
        public string SCHEMENUM { get; set; }
        public string LOT { get; set; }
        public string SOITEMNUM { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public System.DateTime PLANBEGDATE { get; set; }
        public System.DateTime PLANENDDATE { get; set; }
        public string PRODUCTIONLINE { get; set; }
        public string REMARKS { get; set; }
        public decimal WIPQTY { get; set; }
        public int CLOSED { get; set; }
        public Nullable<System.DateTime> CLOSEDDATE { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
    }
}
