//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class METAAB
    {
        public long ID { get; set; }
        public string Module { get; set; }
        public string ModuleAlias { get; set; }
        public byte Level { get; set; }
        public string Entity { get; set; }
        public string ParentEntity { get; set; }
        public string ThisProperties { get; set; }
        public string ThatProperties { get; set; }
        public Nullable<int> Display { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
