//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class METAAA
    {
        public long ID { get; set; }
        public string Entity { get; set; }
        public string EntityAlias { get; set; }
        public string Table { get; set; }
        public string Column { get; set; }
        public string Property { get; set; }
        public string PropertyAlias { get; set; }
        public string Type { get; set; }
        public string RefTable { get; set; }
        public string RefColumn { get; set; }
        public string ThisColumns { get; set; }
        public string ThatColumns { get; set; }
        public Nullable<bool> IsPrimaryKey { get; set; }
        public Nullable<bool> Nullable { get; set; }
        public Nullable<bool> HasDefault { get; set; }
        public string Format { get; set; }
        public Nullable<int> Display { get; set; }
    }
}
