//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIDTL
    {
        public string MINUM { get; set; }
        public string ITEMNUM { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> ISSUEDQTY { get; set; }
        public Nullable<decimal> DOSAGE { get; set; }
        public Nullable<decimal> SCPRATE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<decimal> FREJECTEDQTY { get; set; }
        public Nullable<int> ISREP { get; set; }
        public string MASTERITEMNUM { get; set; }
        public Nullable<int> SEQNUM { get; set; }
        public Nullable<decimal> REPRATE { get; set; }
    }
}
