//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPRESULT
    {
        public int LINEID { get; set; }
        public string MRPCODE { get; set; }
        public string ITEMNUM { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public string ORDERTYPE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string UOM { get; set; }
        public string ORIGIN { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DOCDATE { get; set; }
    }
}
