//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPSCHEME2
    {
        public string MRPCODE { get; set; }
        public string ITEMNUM { get; set; }
        public int PERIODID { get; set; }
        public Nullable<decimal> INITIAL { get; set; }
        public Nullable<decimal> INSTOCK { get; set; }
        public Nullable<decimal> OUTSTOCK { get; set; }
        public Nullable<decimal> FINAL { get; set; }
        public Nullable<decimal> REQUESTS { get; set; }
    }
}
