//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPSCHEME
    {
        public string MRPCODE { get; set; }
        public string DESCR { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string ITEMNUM1 { get; set; }
        public string ITEMNUM2 { get; set; }
        public Nullable<int> EXISTSTOCK { get; set; }
        public Nullable<int> PURCHREQ { get; set; }
        public Nullable<int> PURCHORDER { get; set; }
        public Nullable<int> SALESORDER { get; set; }
        public Nullable<int> WORKORDER { get; set; }
        public Nullable<int> SAFETYQTY { get; set; }
        public string FCTABS { get; set; }
        public string SORTBY { get; set; }
        public Nullable<int> SIMULATION { get; set; }
        public int ISRUNNING { get; set; }
        public Nullable<System.DateTime> LASTSTARTDATE { get; set; }
        public Nullable<System.DateTime> LASTENDDATE { get; set; }
    }
}
