//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPARAM
    {
        public string POCOMMENTS { get; set; }
        public string SCCOMMENTS { get; set; }
        public Nullable<int> EXISTSSUBPR { get; set; }
        public Nullable<int> EXISTSPR { get; set; }
        public Nullable<int> POFIXVENINFO { get; set; }
        public Nullable<int> SCFIXVENINFO { get; set; }
        public Nullable<int> POCANNOTUPDATE { get; set; }
        public Nullable<int> SCCANNOTUPDATE { get; set; }
        public Nullable<int> ALLOWSCGRNOVERACT { get; set; }
        public Nullable<decimal> SCGRNOVERACTRATE { get; set; }
        public Nullable<int> ALLOWOVERMIPLAN { get; set; }
        public Nullable<decimal> OVERMIPLANRATE { get; set; }
        public Nullable<int> POVALIDBUYER { get; set; }
        public Nullable<int> SCVALIDBUYER { get; set; }
        public Nullable<int> PODIFFPRICE { get; set; }
        public Nullable<int> SCDIFFPRICE { get; set; }
        public Nullable<int> REFUNDCHECKRATIO { get; set; }
        public Nullable<int> ALLOWITEMNOTINPO { get; set; }
        public Nullable<int> ALLOWITEMNOTINSC { get; set; }
        public int PURDIFFQTYALLOWPOST { get; set; }
        public int SCPURDIFFQTYALLOWPOST { get; set; }
    }
}
