//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTHAPA
    {
        public string OPNUM { get; set; }
        public string VENID { get; set; }
        public System.DateTime IDATE { get; set; }
        public string DOCNUM { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public string ACCNUM { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string REMARK { get; set; }
        public string DEPTID { get; set; }
        public string PRJCODE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
        public int POST { get; set; }
        public Nullable<int> VNUM { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string INVTYPE { get; set; }
        public Nullable<System.DateTime> CHECKEDSTAMP { get; set; }
        public string CHECKEDUSER { get; set; }
        public Nullable<int> ISCHECKED { get; set; }
    }
}
