//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSTANDINGWO
    {
        public string WONUM { get; set; }
        public System.DateTime WODATE { get; set; }
        public string CREATEDBY { get; set; }
        public string WOSRC { get; set; }
        public string WOTYPE { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public System.DateTime PLANBEGDATE { get; set; }
        public System.DateTime PLANENDDATE { get; set; }
        public Nullable<System.DateTime> SUBMITDATE { get; set; }
        public string WORKSHOP { get; set; }
        public string REMARK { get; set; }
        public int CLOSED { get; set; }
        public decimal WOQTY { get; set; }
        public Nullable<decimal> OUTQTY { get; set; }
        public decimal INQTY { get; set; }
        public string UOM { get; set; }
    }
}
