//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSTANDINGPO
    {
        public string VENID { get; set; }
        public string PONUM { get; set; }
        public string POTYPE { get; set; }
        public System.DateTime IDATE { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public string UOM { get; set; }
        public string EXUOM { get; set; }
        public Nullable<decimal> EXRATE { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public decimal POQTY { get; set; }
        public decimal RECQTY { get; set; }
        public Nullable<decimal> OUTQTY { get; set; }
        public string ITEMDESCR { get; set; }
        public string SPEC { get; set; }
    }
}
