//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSTANDINGSO
    {
        public string CUSID { get; set; }
        public string PONUM { get; set; }
        public string SONUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string ITEMNUM { get; set; }
        public string CUSITEMNUM { get; set; }
        public string LOT { get; set; }
        public string UOM { get; set; }
        public decimal UPRICE { get; set; }
        public decimal SOQTY { get; set; }
        public decimal SIQTY { get; set; }
        public Nullable<decimal> OUTQTY { get; set; }
        public System.DateTime SHIPDATE { get; set; }
        public string REMARK { get; set; }
        public string LABELID { get; set; }
    }
}
