//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWCRTT
    {
        public string RID { get; set; }
        public int ROWID { get; set; }
        public int COLID { get; set; }
        public Nullable<int> WrapText { get; set; }
        public string FORMULA { get; set; }
        public string NumberFormatLocal { get; set; }
        public Nullable<int> MergeAreaRow { get; set; }
        public Nullable<int> MergeAreaColumn { get; set; }
        public Nullable<int> MergeAreaRowsCount { get; set; }
        public Nullable<int> MergeAreaColumnCount { get; set; }
        public Nullable<int> FontBold { get; set; }
        public string FontName { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> FontItalic { get; set; }
        public string FontFontStyle { get; set; }
        public Nullable<int> FontColorIndex { get; set; }
        public Nullable<int> FontUnderline { get; set; }
        public Nullable<int> HorizontalAlignment { get; set; }
        public Nullable<int> VerticalAlignment { get; set; }
        public Nullable<int> BordersxlEdgeLeftLineStyle { get; set; }
        public Nullable<int> BordersxlEdgeLeftWeight { get; set; }
        public Nullable<int> BordersxlEdgeLeftColorIndex { get; set; }
        public Nullable<int> BordersxlEdgeTopLineStyle { get; set; }
        public Nullable<int> BordersxlEdgeTopWeight { get; set; }
        public Nullable<int> BordersxlEdgeTopColorIndex { get; set; }
        public Nullable<int> BordersxlEdgeBottomLineStyle { get; set; }
        public Nullable<int> BordersxlEdgeBottomWeight { get; set; }
        public Nullable<int> BordersxlEdgeBottomColorIndex { get; set; }
        public Nullable<int> BordersxlEdgeRightLineStyle { get; set; }
        public Nullable<int> BordersxlEdgeRightWeight { get; set; }
        public Nullable<int> BordersxlEdgeRightColorIndex { get; set; }
        public Nullable<decimal> ColumnWidth { get; set; }
        public Nullable<int> InteriorColorIndex { get; set; }
        public Nullable<int> InteriorPattern { get; set; }
        public Nullable<int> DisplayGridlines { get; set; }
    }
}
