//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPARAM
    {
        public Nullable<int> ALLOWOUTBOM { get; set; }
        public Nullable<int> ALLOWNONEWO { get; set; }
        public Nullable<int> ALLOWOVERMIPLAN { get; set; }
        public Nullable<int> ALLOWOVERWOPLAN { get; set; }
        public Nullable<int> ADDSCRAP { get; set; }
        public Nullable<decimal> OVRATE { get; set; }
        public Nullable<int> ALLOWNONEMI { get; set; }
        public Nullable<decimal> WIPOVERIN { get; set; }
        public Nullable<int> FIRSTLEVEL { get; set; }
        public Nullable<int> INCLUDEREP { get; set; }
        public Nullable<int> ALLOWUPDPLANDATE { get; set; }
        public Nullable<decimal> OVERMIPLANRATE { get; set; }
        public Nullable<int> EXISTSBOM { get; set; }
        public Nullable<int> AUTOCLOSE { get; set; }
        public Nullable<int> REFUNDAFTERCLOSE { get; set; }
        public Nullable<int> WIPAFTERCLOSE { get; set; }
        public Nullable<int> ALLOWWIPOVERACT { get; set; }
        public Nullable<decimal> WIPOVERACTRATE { get; set; }
        public Nullable<int> REFUNDCHECKRATIO { get; set; }
        public Nullable<int> PROFLOWCONTROL { get; set; }
        public Nullable<decimal> PROFLOWCONTROLRATIO { get; set; }
        public int OWOVERMIPLANBYCUSTOMMI { get; set; }
    }
}
