//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDCTD
    {
        public int FPERIOD { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public Nullable<decimal> QTY1 { get; set; }
        public Nullable<decimal> QTY2 { get; set; }
        public Nullable<decimal> QTY3 { get; set; }
        public Nullable<decimal> QTY4 { get; set; }
        public Nullable<decimal> TOTALQTY { get; set; }
        public string PROLINE { get; set; }
        public Nullable<decimal> STDWRK { get; set; }
        public Nullable<decimal> STDWRKRATE { get; set; }
        public Nullable<decimal> STDWRK2 { get; set; }
        public Nullable<decimal> STDWRK2RATE { get; set; }
        public Nullable<decimal> WORKHOUR { get; set; }
        public Nullable<decimal> WORKHOUR2 { get; set; }
        public Nullable<decimal> LABORCOST { get; set; }
        public Nullable<decimal> FACOVRHAD { get; set; }
        public Nullable<decimal> FUELCOST { get; set; }
        public Nullable<decimal> TOTALWRKHR { get; set; }
        public Nullable<decimal> TOTALWRKHR2 { get; set; }
        public Nullable<decimal> TOTALLABORCOST { get; set; }
        public Nullable<decimal> TOTALFACOVRHAD { get; set; }
        public Nullable<decimal> TOTALFUELCOST { get; set; }
        public Nullable<int> ISREWORK { get; set; }
        public Nullable<decimal> STDLABORCOST { get; set; }
        public Nullable<decimal> STDFACOVRHAD { get; set; }
        public Nullable<decimal> STDFUELCOST { get; set; }
        public Nullable<decimal> STDMATCOST { get; set; }
        public Nullable<decimal> TOTALSTDLABORCOST { get; set; }
        public Nullable<decimal> TOTALSTDFACOVRHAD { get; set; }
        public Nullable<decimal> TOTALSTDFUELCOST { get; set; }
        public Nullable<decimal> TOTALSTDCOST { get; set; }
        public Nullable<decimal> STDUPRICE { get; set; }
        public string PROLINENAME { get; set; }
    }
}
