//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDCTA
    {
        public int FPERIOD { get; set; }
        public string WONUM { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string PROLINE { get; set; }
        public string BKFHLOCID { get; set; }
        public Nullable<decimal> OPENQTY { get; set; }
        public Nullable<decimal> OPENAMT { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> FGQTY { get; set; }
        public Nullable<decimal> FGQTY2 { get; set; }
        public Nullable<decimal> SCRAPQTY { get; set; }
        public Nullable<decimal> FGAMOUNT { get; set; }
        public Nullable<decimal> ENDWIPQTY { get; set; }
        public Nullable<decimal> ENDWIPAMT { get; set; }
        public Nullable<decimal> STDWRK { get; set; }
        public Nullable<decimal> STDWRKRATE { get; set; }
        public Nullable<decimal> STDWRK2 { get; set; }
        public Nullable<decimal> STDWRK2RATE { get; set; }
        public Nullable<decimal> WORKHOUR { get; set; }
        public Nullable<decimal> WORKHOUR2 { get; set; }
        public Nullable<decimal> TOTALWRKHR { get; set; }
        public Nullable<decimal> TOTALWRKHR2 { get; set; }
        public Nullable<decimal> TOTALLABORCOST { get; set; }
        public Nullable<decimal> TOTALFACOVRHAD { get; set; }
        public Nullable<decimal> TOTALFUELCOST { get; set; }
        public Nullable<decimal> LABORCOST { get; set; }
        public Nullable<decimal> FACOVRHAD { get; set; }
        public Nullable<decimal> FUELCOST { get; set; }
        public Nullable<decimal> TOTALCOST { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> DIFFAMOUNT { get; set; }
        public Nullable<decimal> MAINMATCOST { get; set; }
        public Nullable<decimal> BKFHCOST { get; set; }
        public Nullable<decimal> TOTALSTDLABORCOST { get; set; }
        public Nullable<decimal> TOTALSTDFACOVRHAD { get; set; }
        public Nullable<decimal> TOTALSTDFUELCOST { get; set; }
        public Nullable<decimal> TOTALSTDCOST { get; set; }
        public Nullable<decimal> STDUPRICE { get; set; }
        public decimal ADJUSTAMOUNT { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public Nullable<System.DateTime> CLOSEDDATE { get; set; }
        public Nullable<int> ISREWORK { get; set; }
        public string WOTYPE { get; set; }
        public string WOTYPENAME { get; set; }
        public string WOTYPE2 { get; set; }
        public string PROLINENAME { get; set; }
    }
}
