//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDCTB
    {
        public int FPERIOD { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string SONUM { get; set; }
        public Nullable<decimal> WOQTY { get; set; }
        public string PARTNUM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> OPENWIP { get; set; }
        public Nullable<decimal> OPENUPRICE { get; set; }
        public Nullable<decimal> OPENAMT { get; set; }
        public Nullable<decimal> PERIODIN { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> FG1 { get; set; }
        public Nullable<decimal> FG2 { get; set; }
        public Nullable<decimal> FG3 { get; set; }
        public Nullable<decimal> FG4 { get; set; }
        public Nullable<decimal> FGQTY { get; set; }
        public Nullable<decimal> FGUPRICE { get; set; }
        public Nullable<decimal> FGAMOUNT { get; set; }
        public Nullable<decimal> ENDWIP { get; set; }
        public Nullable<decimal> ENDWIPUPRICE { get; set; }
        public Nullable<decimal> ENDWIPAMT { get; set; }
        public Nullable<decimal> DOSAGE { get; set; }
        public Nullable<decimal> SCRAPQTY { get; set; }
        public Nullable<int> ISREWORK { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public Nullable<System.DateTime> CLOSEDDATE { get; set; }
        public Nullable<int> ISBKFLSH { get; set; }
        public Nullable<decimal> TOTALFG1 { get; set; }
        public Nullable<decimal> TOTALFG2 { get; set; }
        public Nullable<decimal> TOTALFG3 { get; set; }
        public Nullable<decimal> TOTALFG4 { get; set; }
        public Nullable<decimal> TOTALFGQTY { get; set; }
        public string BKFHLOCID { get; set; }
        public int ISUNLIMITED { get; set; }
    }
}
