//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDIN3
    {
        public int FPERIOD { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public decimal LASTUPRICE { get; set; }
        public decimal LASTQTY { get; set; }
        public decimal LASTAMOUNT { get; set; }
        public decimal UPRICE { get; set; }
        public decimal QTY { get; set; }
        public decimal AMOUNT { get; set; }
        public int ISOPEN { get; set; }
        public string BKFHLOCID { get; set; }
        public Nullable<decimal> DOSAGE { get; set; }
        public Nullable<int> ISREWORK { get; set; }
    }
}
