//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDINB
    {
        public long ID { get; set; }
        public int FPERIOD { get; set; }
        public string DOCNUM { get; set; }
        public string WONUM { get; set; }
        public string VENID { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> QTY1 { get; set; }
        public Nullable<decimal> QTY2 { get; set; }
        public Nullable<decimal> QTY3 { get; set; }
        public Nullable<decimal> QTY4 { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> NONETAXUPRICE { get; set; }
        public Nullable<decimal> NONETAXAMOUNT { get; set; }
        public string REMARK { get; set; }
        public string LOCID { get; set; }
    }
}
