//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDRTA
    {
        public int FPERIOD { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> MQTY { get; set; }
        public Nullable<decimal> YQTY { get; set; }
        public Nullable<decimal> LYAVGUCOST { get; set; }
        public Nullable<decimal> YPUCOST { get; set; }
        public Nullable<decimal> MACTUCOST { get; set; }
        public Nullable<decimal> YACTAVGUCOST { get; set; }
        public Nullable<decimal> MLTAMT { get; set; }
        public Nullable<decimal> MYPAMT { get; set; }
        public Nullable<decimal> MACTAMT { get; set; }
        public Nullable<decimal> YLACTAMT { get; set; }
        public Nullable<decimal> YYPAMT { get; set; }
        public Nullable<decimal> YYACTAMT { get; set; }
    }
}
