//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDSTM
    {
        public int FPERIOD { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> LASTUPRICE { get; set; }
        public Nullable<decimal> LASTQTY { get; set; }
        public Nullable<decimal> LASTQTY1 { get; set; }
        public Nullable<decimal> LASTQTY2 { get; set; }
        public Nullable<decimal> LASTQTY3 { get; set; }
        public Nullable<decimal> LASTAMOUNT { get; set; }
        public Nullable<decimal> WIPQTY { get; set; }
        public Nullable<decimal> WIPQTY1 { get; set; }
        public Nullable<decimal> WIPQTY2 { get; set; }
        public Nullable<decimal> WIPQTY3 { get; set; }
        public Nullable<decimal> WIPPRICE { get; set; }
        public Nullable<decimal> WIPAMOUNT { get; set; }
        public Nullable<decimal> SIQTY { get; set; }
        public Nullable<decimal> SIQTY1 { get; set; }
        public Nullable<decimal> SIQTY2 { get; set; }
        public Nullable<decimal> SIQTY3 { get; set; }
        public Nullable<decimal> SIPRICE { get; set; }
        public Nullable<decimal> SIAMOUNT { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> QTY1 { get; set; }
        public Nullable<decimal> QTY2 { get; set; }
        public Nullable<decimal> QTY3 { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> DIFFAMOUNT { get; set; }
        public Nullable<bool> HASSIPRICE { get; set; }
    }
}
