//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDTL
    {
        public string PRNUM { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public decimal QTY { get; set; }
        public Nullable<decimal> ORDQTY { get; set; }
        public System.DateTime ADPODATE { get; set; }
        public string PURPOSE { get; set; }
        public string VENID { get; set; }
        public Nullable<int> LEADTIME { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> RESPONSEDATE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public int STATUS { get; set; }
        public decimal POQTY { get; set; }
        public string SUITENUM { get; set; }
        public string SUITENAME { get; set; }
        public Nullable<decimal> SUITEQTY { get; set; }
    }
}
