//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGSA
    {
        public string PREGSNUM { get; set; }
        public System.DateTime PREGSDATE { get; set; }
        public string SNNUM { get; set; }
        public string CUSID { get; set; }
        public Nullable<System.DateTime> SHIPDATE { get; set; }
        public string REMARKS { get; set; }
        public int ISCONFIRMED { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
    }
}
