//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRLSCB
    {
        public string PRLSCNUM { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public decimal SYSQTY { get; set; }
        public Nullable<decimal> SCQTY { get; set; }
        public string UOM { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
    }
}
