//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRORECORDDTL
    {
        public string PRORECNUM { get; set; }
        public int SEQNUM { get; set; }
        public string TEAM { get; set; }
        public string DEVICE { get; set; }
        public string PERDAY { get; set; }
        public string HR { get; set; }
        public string MU { get; set; }
        public decimal QTY { get; set; }
        public decimal PASSQTY { get; set; }
        public Nullable<int> ISDISPATCH { get; set; }
        public string REMARK { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public string UPDATEUSER { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
    }
}
