//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSCH
    {
        public string WONUM { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public System.DateTime SCHEDATE { get; set; }
        public string WRKPROCID { get; set; }
        public string PROLINEID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<int> ISMANUAL { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEBY { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
