//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURINV
    {
        public string PINUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string VENID { get; set; }
        public string INVTYPE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string INVNUM { get; set; }
        public Nullable<System.DateTime> INVDATE { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public decimal AMT { get; set; }
        public decimal BASEAMT { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string REMARK { get; set; }
        public int APPROVE { get; set; }
        public Nullable<System.DateTime> APPROVED { get; set; }
        public string APPROVEDBY { get; set; }
        public Nullable<int> VNUM { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public Nullable<decimal> SELECTEDBASEAMT { get; set; }
        public string CREATEDBY { get; set; }
        public string BUYER { get; set; }
        public Nullable<int> ISRECONCILED { get; set; }
        public string RECINVNUM { get; set; }
        public Nullable<decimal> TAXAMOUNT { get; set; }
    }
}
