//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURIEN
    {
        public string PINUM { get; set; }
        public string GRNNUM { get; set; }
        public string PONUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal BASEAMOUNT { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
    }
}
