//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURRET
    {
        public string PRTNUM { get; set; }
        public string PONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public decimal EXREJECT { get; set; }
        public decimal UPRICE { get; set; }
        public string EXUOM { get; set; }
        public decimal REJECT { get; set; }
        public string UOM { get; set; }
        public decimal AMOUNT { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> REJECTEDQTY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
        public string DRN { get; set; }
        public string INVACCNUM { get; set; }
        public Nullable<int> ISREPLENISH { get; set; }
        public Nullable<decimal> REPLENISHQTY { get; set; }
    }
}
