//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC
    {
        public string QCNUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string DOCNUM { get; set; }
        public string WORKPROC { get; set; }
        public string WORKSHOP { get; set; }
        public string PROLINE { get; set; }
        public string INSPECTOR { get; set; }
        public string WONUM { get; set; }
        public decimal QTY { get; set; }
        public decimal CHECKQTY { get; set; }
        public decimal SAMPLEQTY { get; set; }
        public decimal DEFECTQTY { get; set; }
        public string DEFECTHANDLING { get; set; }
        public string HANDLING { get; set; }
        public string REMARK { get; set; }
        public string QCTEAM { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
    }
}
