//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERYA
    {
        public long Id { get; set; }
        public string Module { get; set; }
        public string Entity { get; set; }
        public string Property { get; set; }
        public string PropertyAlias { get; set; }
        public string Type { get; set; }
        public byte Row { get; set; }
        public byte Column { get; set; }
        public string DefaultValue { get; set; }
        public string Option { get; set; }
        public Nullable<int> NotHandle { get; set; }
    }
}
