//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATION
    {
        public string QTNUM { get; set; }
        public System.DateTime QTDATE { get; set; }
        public string CUSID { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public decimal TAXRATE { get; set; }
        public string PAYMETHOD { get; set; }
        public string PAYTERM { get; set; }
        public string TRADETERM { get; set; }
        public string REV { get; set; }
        public string SALESREGION { get; set; }
        public string SALESREP { get; set; }
        public string SHIPVIA { get; set; }
        public string SHIPTO { get; set; }
        public string REMARK { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string INVTYPE { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<decimal> INSURE { get; set; }
        public Nullable<decimal> HANDLE { get; set; }
        public Nullable<decimal> DELIVERYCHRG { get; set; }
        public Nullable<decimal> MISCHRG { get; set; }
        public string MISCHRGTIT { get; set; }
        public string MISCACC { get; set; }
        public string BANKNAME { get; set; }
        public string ACCOUNTNUM { get; set; }
        public string ACCOUNTNAME { get; set; }
        public string SONUM { get; set; }
        public Nullable<int> ISGENSO { get; set; }
        public Nullable<int> FSTATUS { get; set; }
        public string SOTYPE { get; set; }
        public string QUTYPE { get; set; }
        public string CUSPONUM { get; set; }
    }
}
