//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATIONDTL
    {
        public string QTNUM { get; set; }
        public string ITEMNUM { get; set; }
        public System.DateTime SHIPDATE { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public decimal UPRICE { get; set; }
        public string REMARK { get; set; }
        public string LOT { get; set; }
        public string CUSITEMNUM { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> PLANDATE { get; set; }
        public Nullable<decimal> VFAMIN { get; set; }
        public Nullable<decimal> VFAMAX { get; set; }
        public Nullable<decimal> WDAMIN { get; set; }
        public Nullable<decimal> WDAMAX { get; set; }
        public Nullable<decimal> IVAMIN { get; set; }
        public Nullable<decimal> IVAMAX { get; set; }
        public Nullable<decimal> VFBMIN { get; set; }
        public Nullable<decimal> VFBMAX { get; set; }
        public Nullable<decimal> IVBMIN { get; set; }
        public Nullable<decimal> IVBMAX { get; set; }
        public Nullable<decimal> WDBMIN { get; set; }
        public Nullable<decimal> WDBMAX { get; set; }
        public Nullable<decimal> VFCMIN { get; set; }
        public Nullable<decimal> VFCMAX { get; set; }
        public Nullable<decimal> IVCMIN { get; set; }
        public Nullable<decimal> IVCMAX { get; set; }
        public Nullable<decimal> WDCMIN { get; set; }
        public Nullable<decimal> WDCMAX { get; set; }
        public string POS1 { get; set; }
        public string POS2 { get; set; }
        public int STATUS { get; set; }
        public decimal FUTUREYIELD { get; set; }
        public int ISGIFT { get; set; }
        public Nullable<System.DateTime> SHIPDATE2 { get; set; }
        public Nullable<decimal> CTMIN { get; set; }
        public Nullable<decimal> CTMAX { get; set; }
        public Nullable<decimal> FLUXMIN { get; set; }
        public Nullable<decimal> FLUXMAX { get; set; }
    }
}
