//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANKSTDDTL
    {
        public string RANKCODE { get; set; }
        public string RANKTYPE { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> RANGE1 { get; set; }
        public Nullable<decimal> RANGE2 { get; set; }
        public string RANGEUOM { get; set; }
        public Nullable<decimal> POS1X { get; set; }
        public Nullable<decimal> POS1Y { get; set; }
        public Nullable<decimal> POS2X { get; set; }
        public Nullable<decimal> POS2Y { get; set; }
        public Nullable<decimal> POS3X { get; set; }
        public Nullable<decimal> POS3Y { get; set; }
        public Nullable<decimal> POS4X { get; set; }
        public Nullable<decimal> POS4Y { get; set; }
    }
}
