//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPINVA
    {
        public string RPINVNUM { get; set; }
        public System.DateTime RPINVDATE { get; set; }
        public string LOCID { get; set; }
        public string CUSID { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public string INVTYPE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string VIA { get; set; }
        public string EXPNUM { get; set; }
        public string REMARKS { get; set; }
        public string SALESREP { get; set; }
        public string SALESREGION { get; set; }
        public decimal TOTALQTY { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public int COMPLETED { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
