//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTEXCEL
    {
        public string PRONAME { get; set; }
        public string FIELDNAME { get; set; }
        public string CHNAME { get; set; }
        public string ENGNAME { get; set; }
        public string STYLE { get; set; }
        public int SEQNUM { get; set; }
        public string TYPE { get; set; }
    }
}
