//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESINVOICE
    {
        public string SINVNUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string INVNUM { get; set; }
        public System.DateTime INVDATE { get; set; }
        public string INVTYPE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string CUSID { get; set; }
        public string PAYTERM { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal BASEAMOUNT { get; set; }
        public string PAYMETHOD { get; set; }
        public string REMARK { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public string APPROVEDBY { get; set; }
        public Nullable<System.DateTime> APPROVEDSTAMP { get; set; }
        public int POST { get; set; }
        public Nullable<int> VNUM { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public Nullable<int> ISRECONCILED { get; set; }
        public string RECINVNUM { get; set; }
        public string SSTATNUM { get; set; }
        public Nullable<System.DateTime> SSTATSTAMP { get; set; }
        public string SSTATUSER { get; set; }
        public int ISTAXINV { get; set; }
        public Nullable<decimal> TAXAMOUNT { get; set; }
    }
}
