//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESPERSON
    {
        public string CODE { get; set; }
        public string DESCR { get; set; }
        public string UID { get; set; }
        public int ISDENY { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string SALESREGION { get; set; }
        public string SUPERVISOR { get; set; }
        public string DESCRENG { get; set; }
    }
}
