//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPSTDDTL
    {
        public string CODE { get; set; }
        public int SEQNUM { get; set; }
        public Nullable<decimal> LOTSIZE { get; set; }
        public Nullable<decimal> SQMPQTY { get; set; }
        public string FORMULA { get; set; }
        public Nullable<decimal> AQQTY1 { get; set; }
        public Nullable<decimal> REQTY1 { get; set; }
        public Nullable<decimal> ACQTY2 { get; set; }
        public Nullable<decimal> REQTY2 { get; set; }
    }
}
