//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMIWP
    {
        public string SWNUM { get; set; }
        public System.DateTime IDATE { get; set; }
        public string SWTYPE { get; set; }
        public string LOCID { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string UOM { get; set; }
        public string WORKPROC { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> TOTALQTY { get; set; }
        public Nullable<int> COMPLETED { get; set; }
        public string CREATEDBY { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
    }
}
