//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINVDTL
    {
        public string SINUM { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public decimal UPRICE { get; set; }
        public string UOM { get; set; }
        public decimal AMOUNT { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public decimal CUSTOMPRICE { get; set; }
        public string CUSPONUM { get; set; }
        public string PSNUM { get; set; }
        public Nullable<int> ISSELECTED { get; set; }
        public string SELECTEDUID { get; set; }
        public string INVNUM { get; set; }
        public long SEQNUM { get; set; }
    }
}
