//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO
    {
        public string SONUM { get; set; }
        public string SOTYPE { get; set; }
        public string CUSID { get; set; }
        public System.DateTime IDATE { get; set; }
        public string REV { get; set; }
        public string PONUM { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string PAYTERM { get; set; }
        public string TRADETERM { get; set; }
        public string SHIPMARK { get; set; }
        public string VIA { get; set; }
        public string REMARK { get; set; }
        public string SOLDTO { get; set; }
        public string SHIPTO { get; set; }
        public string BILLTO { get; set; }
        public string SALESREP { get; set; }
        public string PROJECT { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public Nullable<int> CANCELED { get; set; }
        public string CREATEDBY { get; set; }
        public int STATUS { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public string SOINVTYPE { get; set; }
        public Nullable<decimal> INSURE { get; set; }
        public Nullable<decimal> HANDLE { get; set; }
        public Nullable<decimal> DELIVERYCHRG { get; set; }
        public Nullable<decimal> MISCHRG { get; set; }
        public string MISCHRGTIT { get; set; }
        public string MISCACC { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public string BANKNAME { get; set; }
        public string ACCOUNTNUM { get; set; }
        public string ACCOUNTNAME { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public Nullable<decimal> TOTALQTY { get; set; }
        public Nullable<int> PRNCOUNT { get; set; }
        public string QTNUM { get; set; }
    
        public virtual PAYMETHOD PAYMETHOD { get; set; }
        public virtual SALESREGION SALESREGION { get; set; }
    }
}
