//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOPRVC
    {
        public int SOPRVC_ID { get; set; }
        public int SOPROREQUIRE_ID { get; set; }
        public int GRAMPB_ID { get; set; }
        public Nullable<int> SOPRVD_ID { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> Z { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
