//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPARAM
    {
        public int ISCHECKRANK { get; set; }
        public Nullable<int> DISPRANKDATA { get; set; }
        public Nullable<int> ALLOWOVERREQ { get; set; }
        public Nullable<int> ALLOWOVERR { get; set; }
        public Nullable<int> CHKDEPTID { get; set; }
        public Nullable<int> UNIONDOCNUM { get; set; }
        public Nullable<int> ALLOWUPDDATE { get; set; }
        public Nullable<int> OVERINVENTORY { get; set; }
        public Nullable<int> ALLOWUPDATEUPRICE { get; set; }
        public int ALLOWUPDRMK { get; set; }
        public Nullable<int> DISPCUSNAME { get; set; }
        public int DICDATEIDENTICAL { get; set; }
        public Nullable<int> DIFFQTYALLOWPOST { get; set; }
        public Nullable<int> ALLOWITEMNOTINSO { get; set; }
        public Nullable<int> REFCONTRACTAPPROVAL { get; set; }
        public int ALLOWNONEINVOICEAPPLY { get; set; }
        public int ALLOWNONETAXRATE { get; set; }
        public int QUOTATIONDTLROWCOUNT { get; set; }
        public int DELETEENTIRESINV { get; set; }
        public int DELETEENTIRESR { get; set; }
        public int AllSONUMNOTINSO { get; set; }
        public int SRDIFFQTYALLOWPOST { get; set; }
        public int NEEDQUOTATION { get; set; }
    }
}
