//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRAPPA
    {
        public string SRAPPNUM { get; set; }
        public System.DateTime SRAPPDATE { get; set; }
        public string CUSID { get; set; }
        public string DEPTID { get; set; }
        public string SALESREP { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public string INVTYPE { get; set; }
        public decimal TAXRATE { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public string REFUNDREASON { get; set; }
        public string REMARKS { get; set; }
        public int ISCONFIRMED { get; set; }
        public string SRNUM { get; set; }
        public string WFSTATUS { get; set; }
        public string ISPRINTED { get; set; }
        public string OBJTYPE { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
        public string UPDATEUSER { get; set; }
        public string SALESREGION { get; set; }
    }
}
