//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSTATB
    {
        public string SSTATNUM { get; set; }
        public string SINVNUM { get; set; }
        public System.DateTime SINVDATE { get; set; }
        public string INVNUM { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
    }
}
