//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSTATA
    {
        public string SSTATNUM { get; set; }
        public string CUSID { get; set; }
        public System.DateTime SSTATDATE { get; set; }
        public string TITLES { get; set; }
        public System.DateTime INVOICEDATE1 { get; set; }
        public System.DateTime INVOICEDATE2 { get; set; }
        public string REAMRKS { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public int ISINREFUND { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
    }
}
