//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class swerpEntities : DbContext
    {
        public swerpEntities()
            : base("name=swerpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC> ACCs { get; set; }
        public virtual DbSet<ACCCATEGORY> ACCCATEGORies { get; set; }
        public virtual DbSet<ACCPROJECT> ACCPROJECTs { get; set; }
        public virtual DbSet<ACCRPT> ACCRPTs { get; set; }
        public virtual DbSet<ACCRPTCATEGORY> ACCRPTCATEGORies { get; set; }
        public virtual DbSet<ACCRPTCOMPANY> ACCRPTCOMPANies { get; set; }
        public virtual DbSet<ACCRPTDEPARTMENT> ACCRPTDEPARTMENTs { get; set; }
        public virtual DbSet<ACCRPTDTL> ACCRPTDTLs { get; set; }
        public virtual DbSet<ACCRPTJOUTYPE> ACCRPTJOUTYPEs { get; set; }
        public virtual DbSet<ACCRPTPROJECT> ACCRPTPROJECTs { get; set; }
        public virtual DbSet<ACCTYPE> ACCTYPEs { get; set; }
        public virtual DbSet<APAY> APAYs { get; set; }
        public virtual DbSet<APAYADJUST> APAYADJUSTs { get; set; }
        public virtual DbSet<APAYADJUSTDTL> APAYADJUSTDTLs { get; set; }
        public virtual DbSet<APAYDC> APAYDCs { get; set; }
        public virtual DbSet<APAYDTL> APAYDTLs { get; set; }
        public virtual DbSet<APCLET> APCLETs { get; set; }
        public virtual DbSet<APPLOG> APPLOGs { get; set; }
        public virtual DbSet<APPTKT> APPTKTs { get; set; }
        public virtual DbSet<APREQA> APREQAs { get; set; }
        public virtual DbSet<APREQB> APREQBs { get; set; }
        public virtual DbSet<APRFND> APRFNDs { get; set; }
        public virtual DbSet<AQL> AQLs { get; set; }
        public virtual DbSet<ARCLET> ARCLETs { get; set; }
        public virtual DbSet<AREC> ARECs { get; set; }
        public virtual DbSet<ARECADJUST> ARECADJUSTs { get; set; }
        public virtual DbSet<ARECADJUSTDTL> ARECADJUSTDTLs { get; set; }
        public virtual DbSet<ARECDC> ARECDCs { get; set; }
        public virtual DbSet<ARECDTL> ARECDTLs { get; set; }
        public virtual DbSet<BANKAC> BANKACs { get; set; }
        public virtual DbSet<BEGITEMSBAL> BEGITEMSBALs { get; set; }
        public virtual DbSet<BEGPAYBAL> BEGPAYBALs { get; set; }
        public virtual DbSet<BEGRECBAL> BEGRECBALs { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<BOMDTL> BOMDTLs { get; set; }
        public virtual DbSet<BOMSCA> BOMSCAs { get; set; }
        public virtual DbSet<BOMSCB> BOMSCBs { get; set; }
        public virtual DbSet<BOOKMARK> BOOKMARKs { get; set; }
        public virtual DbSet<BTNMNU> BTNMNUs { get; set; }
        public virtual DbSet<BUYER> BUYERs { get; set; }
        public virtual DbSet<COMINF> COMINFs { get; set; }
        public virtual DbSet<COORAA> COORAAs { get; set; }
        public virtual DbSet<COORAB> COORABs { get; set; }
        public virtual DbSet<CRAPLY> CRAPLies { get; set; }
        public virtual DbSet<CSTACC> CSTACCs { get; set; }
        public virtual DbSet<CSTBFA> CSTBFAs { get; set; }
        public virtual DbSet<CSTBFB> CSTBFBs { get; set; }
        public virtual DbSet<CSTCPA> CSTCPAs { get; set; }
        public virtual DbSet<CSTCPB> CSTCPBs { get; set; }
        public virtual DbSet<CSTELT> CSTELTs { get; set; }
        public virtual DbSet<CSTMAA> CSTMAAs { get; set; }
        public virtual DbSet<CSTMAB> CSTMABs { get; set; }
        public virtual DbSet<CSTOPH> CSTOPHs { get; set; }
        public virtual DbSet<CSTRPT> CSTRPTs { get; set; }
        public virtual DbSet<CSTSCA> CSTSCAs { get; set; }
        public virtual DbSet<CSTSCB> CSTSCBs { get; set; }
        public virtual DbSet<CSTSCC> CSTSCCs { get; set; }
        public virtual DbSet<CSTSCD> CSTSCDs { get; set; }
        public virtual DbSet<CURR> CURRs { get; set; }
        public virtual DbSet<CUSEVA> CUSEVAs { get; set; }
        public virtual DbSet<CUSITEM> CUSITEMS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTYPE> CUSTYPEs { get; set; }
        public virtual DbSet<DEFECTHANDLING> DEFECTHANDLINGs { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<DICTAA> DICTAAs { get; set; }
        public virtual DbSet<DICTAB> DICTABs { get; set; }
        public virtual DbSet<DISAMA> DISAMAs { get; set; }
        public virtual DbSet<DISAMB> DISAMBs { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<ECNBOM> ECNBOMs { get; set; }
        public virtual DbSet<ECNBOMDTL> ECNBOMDTLs { get; set; }
        public virtual DbSet<ECNTEA> ECNTEAs { get; set; }
        public virtual DbSet<ECNTEB> ECNTEBs { get; set; }
        public virtual DbSet<EFILEA> EFILEAs { get; set; }
        public virtual DbSet<EFILEB> EFILEBs { get; set; }
        public virtual DbSet<EFILEC> EFILECs { get; set; }
        public virtual DbSet<EFILED> EFILEDs { get; set; }
        public virtual DbSet<EGROUP> EGROUPs { get; set; }
        public virtual DbSet<EINBOX> EINBOXes { get; set; }
        public virtual DbSet<EMEMBR> EMEMBRs { get; set; }
        public virtual DbSet<ENOTE> ENOTES { get; set; }
        public virtual DbSet<EOPTON> EOPTONs { get; set; }
        public virtual DbSet<EXPCOT> EXPCOTs { get; set; }
        public virtual DbSet<EXPORT> EXPORTs { get; set; }
        public virtual DbSet<FACDAR> FACDARs { get; set; }
        public virtual DbSet<FLWDAD> FLWDADs { get; set; }
        public virtual DbSet<FLWDAT> FLWDATs { get; set; }
        public virtual DbSet<FLWMID> FLWMIDs { get; set; }
        public virtual DbSet<FLWNTF> FLWNTFs { get; set; }
        public virtual DbSet<FLWSTP> FLWSTPs { get; set; }
        public virtual DbSet<FLWTPL> FLWTPLs { get; set; }
        public virtual DbSet<FLWUSR> FLWUSRs { get; set; }
        public virtual DbSet<FOMLAA> FOMLAAs { get; set; }
        public virtual DbSet<FOMLAB> FOMLABs { get; set; }
        public virtual DbSet<FPERIOD> FPERIODs { get; set; }
        public virtual DbSet<FXDINV> FXDINVs { get; set; }
        public virtual DbSet<FXDSTM> FXDSTMs { get; set; }
        public virtual DbSet<GRACRA> GRACRAs { get; set; }
        public virtual DbSet<GRACRB> GRACRBs { get; set; }
        public virtual DbSet<GRACRC> GRACRCs { get; set; }
        public virtual DbSet<GRADATA> GRADATAs { get; set; }
        public virtual DbSet<GRADEDATA> GRADEDATAs { get; set; }
        public virtual DbSet<GRADVA> GRADVAs { get; set; }
        public virtual DbSet<GRADVB> GRADVBs { get; set; }
        public virtual DbSet<GRADVC> GRADVCs { get; set; }
        public virtual DbSet<GRADVD> GRADVDs { get; set; }
        public virtual DbSet<GRAMPA> GRAMPAs { get; set; }
        public virtual DbSet<GRAMPB> GRAMPBs { get; set; }
        public virtual DbSet<GRN> GRNs { get; set; }
        public virtual DbSet<GRNDTL> GRNDTLs { get; set; }
        public virtual DbSet<INQUIRY> INQUIRies { get; set; }
        public virtual DbSet<INQUIRYDTL> INQUIRYDTLs { get; set; }
        public virtual DbSet<INSPECTIONITEM> INSPECTIONITEMs { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<INVOICEREQUEST> INVOICEREQUESTs { get; set; }
        public virtual DbSet<INVOICEREQUESTDTL> INVOICEREQUESTDTLs { get; set; }
        public virtual DbSet<INVTYPE> INVTYPEs { get; set; }
        public virtual DbSet<IPLIST> IPLISTs { get; set; }
        public virtual DbSet<IQC> IQCs { get; set; }
        public virtual DbSet<IQCDTL> IQCDTLs { get; set; }
        public virtual DbSet<ITEMCN> ITEMCNs { get; set; }
        public virtual DbSet<ITEMGRP> ITEMGRPs { get; set; }
        public virtual DbSet<ITEMPM> ITEMPMs { get; set; }
        public virtual DbSet<ITEMPV> ITEMPVs { get; set; }
        public virtual DbSet<ITEMRA> ITEMRAs { get; set; }
        public virtual DbSet<ITEMRB> ITEMRBs { get; set; }
        public virtual DbSet<ITEM> ITEMS { get; set; }
        public virtual DbSet<ITEMSP> ITEMSPs { get; set; }
        public virtual DbSet<ITEMTA> ITEMTAs { get; set; }
        public virtual DbSet<ITEMTYPE> ITEMTYPEs { get; set; }
        public virtual DbSet<LPDATA> LPDATAs { get; set; }
        public virtual DbSet<MAGENT> MAGENTs { get; set; }
        public virtual DbSet<MATSCU> MATSCUs { get; set; }
        public virtual DbSet<MATSTM> MATSTMs { get; set; }
        public virtual DbSet<MENUITEM> MENUITEMs { get; set; }
        public virtual DbSet<MESINV> MESINVs { get; set; }
        public virtual DbSet<MESOPA> MESOPAs { get; set; }
        public virtual DbSet<MESRFA> MESRFAs { get; set; }
        public virtual DbSet<MESRFB> MESRFBs { get; set; }
        public virtual DbSet<MESSOA> MESSOAs { get; set; }
        public virtual DbSet<MESSOB> MESSOBs { get; set; }
        public virtual DbSet<MESTPA> MESTPAs { get; set; }
        public virtual DbSet<MESTPB> MESTPBs { get; set; }
        public virtual DbSet<MESTPC> MESTPCs { get; set; }
        public virtual DbSet<MESWEA> MESWEAs { get; set; }
        public virtual DbSet<MESWEB> MESWEBs { get; set; }
        public virtual DbSet<MESWOA> MESWOAs { get; set; }
        public virtual DbSet<MESWOB> MESWOBs { get; set; }
        public virtual DbSet<MESWOC> MESWOCs { get; set; }
        public virtual DbSet<METAAA> METAAAs { get; set; }
        public virtual DbSet<METAAB> METAABs { get; set; }
        public virtual DbSet<MI> MIs { get; set; }
        public virtual DbSet<MIBKFH> MIBKFHs { get; set; }
        public virtual DbSet<MIDTL> MIDTLs { get; set; }
        public virtual DbSet<MIDTL2> MIDTL2 { get; set; }
        public virtual DbSet<MITYPE> MITYPEs { get; set; }
        public virtual DbSet<MNUCTG> MNUCTGs { get; set; }
        public virtual DbSet<MODULEACTION> MODULEACTIONs { get; set; }
        public virtual DbSet<MODULE> MODULES { get; set; }
        public virtual DbSet<MR> MRs { get; set; }
        public virtual DbSet<MRDTL> MRDTLs { get; set; }
        public virtual DbSet<MRPINT> MRPINTs { get; set; }
        public virtual DbSet<MRPOUT> MRPOUTs { get; set; }
        public virtual DbSet<MRPRESULT> MRPRESULTs { get; set; }
        public virtual DbSet<MRPRLT> MRPRLTs { get; set; }
        public virtual DbSet<MRPSCA> MRPSCAs { get; set; }
        public virtual DbSet<MRPSCB> MRPSCBs { get; set; }
        public virtual DbSet<MRPSCC> MRPSCCs { get; set; }
        public virtual DbSet<MRPSCHEME> MRPSCHEMEs { get; set; }
        public virtual DbSet<MRPSCHEME1> MRPSCHEME1 { get; set; }
        public virtual DbSet<MRPSCHEME2> MRPSCHEME2 { get; set; }
        public virtual DbSet<MRPSCHEME3> MRPSCHEME3 { get; set; }
        public virtual DbSet<MRTYPE> MRTYPEs { get; set; }
        public virtual DbSet<MYJOB> MYJOBs { get; set; }
        public virtual DbSet<OCURRN> OCURRNs { get; set; }
        public virtual DbSet<OCURTE> OCURTEs { get; set; }
        public virtual DbSet<OGRNEN> OGRNENs { get; set; }
        public virtual DbSet<OPRJCT> OPRJCTs { get; set; }
        public virtual DbSet<OTHAPA> OTHAPAs { get; set; }
        public virtual DbSet<OTHAPD> OTHAPDs { get; set; }
        public virtual DbSet<OTHARA> OTHARAs { get; set; }
        public virtual DbSet<OTHARD> OTHARDs { get; set; }
        public virtual DbSet<OTHEND> OTHENDs { get; set; }
        public virtual DbSet<OTHENT> OTHENTs { get; set; }
        public virtual DbSet<OTHGRN> OTHGRNs { get; set; }
        public virtual DbSet<OWCRPT> OWCRPTs { get; set; }
        public virtual DbSet<OWCRTT> OWCRTTs { get; set; }
        public virtual DbSet<PAYMETHOD> PAYMETHODs { get; set; }
        public virtual DbSet<PAYTERM> PAYTERMs { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<PODTL> PODTLs { get; set; }
        public virtual DbSet<POTYPE> POTYPEs { get; set; }
        public virtual DbSet<PPCAPA> PPCAPAs { get; set; }
        public virtual DbSet<PR> PRs { get; set; }
        public virtual DbSet<PRDCTA> PRDCTAs { get; set; }
        public virtual DbSet<PRDCTB> PRDCTBs { get; set; }
        public virtual DbSet<PRDCTC> PRDCTCs { get; set; }
        public virtual DbSet<PRDCTD> PRDCTDs { get; set; }
        public virtual DbSet<PRDCTE> PRDCTEs { get; set; }
        public virtual DbSet<PRDIN2> PRDIN2 { get; set; }
        public virtual DbSet<PRDIN3> PRDIN3 { get; set; }
        public virtual DbSet<PRDIN4> PRDIN4 { get; set; }
        public virtual DbSet<PRDIN5> PRDIN5 { get; set; }
        public virtual DbSet<PRDIN6> PRDIN6 { get; set; }
        public virtual DbSet<PRDIN7> PRDIN7 { get; set; }
        public virtual DbSet<PRDINB> PRDINBs { get; set; }
        public virtual DbSet<PRDINV> PRDINVs { get; set; }
        public virtual DbSet<PRDOTB> PRDOTBs { get; set; }
        public virtual DbSet<PRDRTA> PRDRTAs { get; set; }
        public virtual DbSet<PRDST2> PRDST2 { get; set; }
        public virtual DbSet<PRDSTM> PRDSTMs { get; set; }
        public virtual DbSet<PRDTL> PRDTLs { get; set; }
        public virtual DbSet<PREGSA> PREGSAs { get; set; }
        public virtual DbSet<PREGSB> PREGSBs { get; set; }
        public virtual DbSet<PRLSCA> PRLSCAs { get; set; }
        public virtual DbSet<PRLSCB> PRLSCBs { get; set; }
        public virtual DbSet<PROCST> PROCSTs { get; set; }
        public virtual DbSet<PROCTA> PROCTAs { get; set; }
        public virtual DbSet<PROCTB> PROCTBs { get; set; }
        public virtual DbSet<PROINA> PROINAs { get; set; }
        public virtual DbSet<PROINB> PROINBs { get; set; }
        public virtual DbSet<PROITEMSCRAP> PROITEMSCRAPs { get; set; }
        public virtual DbSet<PROITEMSCRAPDTL> PROITEMSCRAPDTLs { get; set; }
        public virtual DbSet<PROLINE> PROLINEs { get; set; }
        public virtual DbSet<PRORECORD> PRORECORDs { get; set; }
        public virtual DbSet<PRORECORDDTL> PRORECORDDTLs { get; set; }
        public virtual DbSet<PROSCH> PROSCHes { get; set; }
        public virtual DbSet<PRSYSA> PRSYSAs { get; set; }
        public virtual DbSet<PRSYSB> PRSYSBs { get; set; }
        public virtual DbSet<PUR> PURs { get; set; }
        public virtual DbSet<PURAPA> PURAPAs { get; set; }
        public virtual DbSet<PURAPB> PURAPBs { get; set; }
        public virtual DbSet<PURDTL> PURDTLs { get; set; }
        public virtual DbSet<PURIEN> PURIENs { get; set; }
        public virtual DbSet<PURIND> PURINDs { get; set; }
        public virtual DbSet<PURINV> PURINVs { get; set; }
        public virtual DbSet<PURRET> PURRETs { get; set; }
        public virtual DbSet<PWKGRP> PWKGRPs { get; set; }
        public virtual DbSet<QC> QCs { get; set; }
        public virtual DbSet<QCDTL> QCDTLs { get; set; }
        public virtual DbSet<QCITEM> QCITEMs { get; set; }
        public virtual DbSet<QCMETHOD> QCMETHODs { get; set; }
        public virtual DbSet<QCSCHM> QCSCHMs { get; set; }
        public virtual DbSet<QCTEAM> QCTEAMs { get; set; }
        public virtual DbSet<QCWORKPROC> QCWORKPROCs { get; set; }
        public virtual DbSet<QUERYA> QUERYAs { get; set; }
        public virtual DbSet<QUOTATION> QUOTATIONs { get; set; }
        public virtual DbSet<QUOTATIONDTL> QUOTATIONDTLs { get; set; }
        public virtual DbSet<QUTYPE> QUTYPEs { get; set; }
        public virtual DbSet<RANKING> RANKINGs { get; set; }
        public virtual DbSet<RANKINGDTL> RANKINGDTLs { get; set; }
        public virtual DbSet<RANKSTD> RANKSTDs { get; set; }
        public virtual DbSet<RANKSTDDTL> RANKSTDDTLs { get; set; }
        public virtual DbSet<REGHOR> REGHORs { get; set; }
        public virtual DbSet<REPACKING> REPACKINGs { get; set; }
        public virtual DbSet<REPACKINGDTL> REPACKINGDTLs { get; set; }
        public virtual DbSet<REPORT> REPORTS { get; set; }
        public virtual DbSet<ROLEACTION> ROLEACTIONs { get; set; }
        public virtual DbSet<RPINVA> RPINVAs { get; set; }
        public virtual DbSet<RPINVB> RPINVBs { get; set; }
        public virtual DbSet<RPTEXCEL> RPTEXCELs { get; set; }
        public virtual DbSet<SALESINVOICE> SALESINVOICEs { get; set; }
        public virtual DbSet<SALESINVOICEDTL> SALESINVOICEDTLs { get; set; }
        public virtual DbSet<SALESPERSON> SALESPERSONs { get; set; }
        public virtual DbSet<SALESREGION> SALESREGIONs { get; set; }
        public virtual DbSet<SALRPA> SALRPAs { get; set; }
        public virtual DbSet<SALRPB> SALRPBs { get; set; }
        public virtual DbSet<SAMPSTD> SAMPSTDs { get; set; }
        public virtual DbSet<SAMPSTDDTL> SAMPSTDDTLs { get; set; }
        public virtual DbSet<SCCSTA> SCCSTAs { get; set; }
        public virtual DbSet<SCCSTB> SCCSTBs { get; set; }
        public virtual DbSet<SCCSTC> SCCSTCs { get; set; }
        public virtual DbSet<SCCSTD> SCCSTDs { get; set; }
        public virtual DbSet<SEMIWD> SEMIWDs { get; set; }
        public virtual DbSet<SEMIWP> SEMIWPs { get; set; }
        public virtual DbSet<SETPRN> SETPRNs { get; set; }
        public virtual DbSet<SHIPPINGNOTE> SHIPPINGNOTEs { get; set; }
        public virtual DbSet<SHIPPINGNOTEDTL> SHIPPINGNOTEDTLs { get; set; }
        public virtual DbSet<SINV> SINVs { get; set; }
        public virtual DbSet<SINVDATA> SINVDATAs { get; set; }
        public virtual DbSet<SINVDTL> SINVDTLs { get; set; }
        public virtual DbSet<SINVDTL2> SINVDTL2 { get; set; }
        public virtual DbSet<SINVDTL3> SINVDTL3 { get; set; }
        public virtual DbSet<SO> SOes { get; set; }
        public virtual DbSet<SOACYA> SOACYAs { get; set; }
        public virtual DbSet<SOACYB> SOACYBs { get; set; }
        public virtual DbSet<SODTL> SODTLs { get; set; }
        public virtual DbSet<SOFILE> SOFILEs { get; set; }
        public virtual DbSet<SOPROREQUIRE> SOPROREQUIREs { get; set; }
        public virtual DbSet<SOPRVA> SOPRVAs { get; set; }
        public virtual DbSet<SOPRVB> SOPRVBs { get; set; }
        public virtual DbSet<SOPRVC> SOPRVCs { get; set; }
        public virtual DbSet<SOPRVD> SOPRVDs { get; set; }
        public virtual DbSet<SOREVW> SOREVWs { get; set; }
        public virtual DbSet<SOTYPE> SOTYPEs { get; set; }
        public virtual DbSet<SR> SRs { get; set; }
        public virtual DbSet<SRAPPA> SRAPPAs { get; set; }
        public virtual DbSet<SRAPPB> SRAPPBs { get; set; }
        public virtual DbSet<SRCTYPE> SRCTYPEs { get; set; }
        public virtual DbSet<SRDATA> SRDATAs { get; set; }
        public virtual DbSet<SRDTL> SRDTLs { get; set; }
        public virtual DbSet<SRDTL2> SRDTL2 { get; set; }
        public virtual DbSet<SSTATA> SSTATAs { get; set; }
        public virtual DbSet<SSTATB> SSTATBs { get; set; }
        public virtual DbSet<ST> STs { get; set; }
        public virtual DbSet<STDTL> STDTLs { get; set; }
        public virtual DbSet<STDWKF> STDWKFs { get; set; }
        public virtual DbSet<STOCKADJUST> STOCKADJUSTs { get; set; }
        public virtual DbSet<STOCKADJUSTDTL> STOCKADJUSTDTLs { get; set; }
        public virtual DbSet<STOCKCOUNT> STOCKCOUNTs { get; set; }
        public virtual DbSet<STOCKCOUNTDTL> STOCKCOUNTDTLs { get; set; }
        public virtual DbSet<SUBGRN> SUBGRNs { get; set; }
        public virtual DbSet<SUBGRNDTL> SUBGRNDTLs { get; set; }
        public virtual DbSet<SUBSOA> SUBSOAs { get; set; }
        public virtual DbSet<SUBSOD> SUBSODs { get; set; }
        public virtual DbSet<SYLOCK> SYLOCKs { get; set; }
        public virtual DbSet<SYSPARAMETER> SYSPARAMETERs { get; set; }
        public virtual DbSet<SYSPARVALUE> SYSPARVALUEs { get; set; }
        public virtual DbSet<TRADETERM> TRADETERMs { get; set; }
        public virtual DbSet<TSKUSR> TSKUSRs { get; set; }
        public virtual DbSet<UNSCWA> UNSCWAs { get; set; }
        public virtual DbSet<UNSCWB> UNSCWBs { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<URPTAA> URPTAAs { get; set; }
        public virtual DbSet<URPTAB> URPTABs { get; set; }
        public virtual DbSet<URPTAC> URPTACs { get; set; }
        public virtual DbSet<URPTAD> URPTADs { get; set; }
        public virtual DbSet<URPTAE> URPTAEs { get; set; }
        public virtual DbSet<USERLOG> USERLOGs { get; set; }
        public virtual DbSet<USEROP> USEROPs { get; set; }
        public virtual DbSet<USERROLE> USERROLES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USRPRF> USRPRFs { get; set; }
        public virtual DbSet<VBSTYP> VBSTYPs { get; set; }
        public virtual DbSet<VENDOR> VENDORs { get; set; }
        public virtual DbSet<VENEVA> VENEVAs { get; set; }
        public virtual DbSet<VENITEM> VENITEMS { get; set; }
        public virtual DbSet<VENTYPE> VENTYPEs { get; set; }
        public virtual DbSet<VOUCHR> VOUCHRs { get; set; }
        public virtual DbSet<VOUENY> VOUENies { get; set; }
        public virtual DbSet<WAFERDATA> WAFERDATAs { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSEs { get; set; }
        public virtual DbSet<WHPLNE> WHPLNEs { get; set; }
        public virtual DbSet<WHQRYA> WHQRYAs { get; set; }
        public virtual DbSet<WIP> WIPs { get; set; }
        public virtual DbSet<WIPDTL> WIPDTLs { get; set; }
        public virtual DbSet<WIPDTL2> WIPDTL2 { get; set; }
        public virtual DbSet<WIPTYPE> WIPTYPEs { get; set; }
        public virtual DbSet<WMSTER> WMSTERs { get; set; }
        public virtual DbSet<WO> WOes { get; set; }
        public virtual DbSet<WONLNE> WONLNEs { get; set; }
        public virtual DbSet<WORKPROC> WORKPROCs { get; set; }
        public virtual DbSet<WORKSHOP> WORKSHOPs { get; set; }
        public virtual DbSet<WOTYPE> WOTYPEs { get; set; }
        public virtual DbSet<WPBOMA> WPBOMAs { get; set; }
        public virtual DbSet<WPBOMB> WPBOMBs { get; set; }
        public virtual DbSet<WPCAPA> WPCAPAs { get; set; }
        public virtual DbSet<WRKPRC> WRKPRCs { get; set; }
        public virtual DbSet<BKFOTA> BKFOTAs { get; set; }
        public virtual DbSet<BKFOUT> BKFOUTs { get; set; }
        public virtual DbSet<CSTCPC> CSTCPCs { get; set; }
        public virtual DbSet<CSTCPD> CSTCPDs { get; set; }
        public virtual DbSet<CSTCPE> CSTCPEs { get; set; }
        public virtual DbSet<CSTPAM> CSTPAMs { get; set; }
        public virtual DbSet<FXDINA> FXDINAs { get; set; }
        public virtual DbSet<FXDOUT> FXDOUTs { get; set; }
        public virtual DbSet<MATINA> MATINAs { get; set; }
        public virtual DbSet<MATOUT> MATOUTs { get; set; }
        public virtual DbSet<MPARAM> MPARAMs { get; set; }
        public virtual DbSet<OPARAM> OPARAMs { get; set; }
        public virtual DbSet<PPARAM> PPARAMs { get; set; }
        public virtual DbSet<PRDINA> PRDINAs { get; set; }
        public virtual DbSet<PRDOUT> PRDOUTs { get; set; }
        public virtual DbSet<SPARAM> SPARAMs { get; set; }
        public virtual DbSet<SYSTEMINIT> SYSTEMINITs { get; set; }
        public virtual DbSet<VersionInfo> VersionInfoes { get; set; }
        public virtual DbSet<AVLSALESREJECT> AVLSALESREJECTs { get; set; }
        public virtual DbSet<LACC> LACCs { get; set; }
        public virtual DbSet<OUTSTANDINGPO> OUTSTANDINGPOes { get; set; }
        public virtual DbSet<OUTSTANDINGPR> OUTSTANDINGPRs { get; set; }
        public virtual DbSet<OUTSTANDINGSO> OUTSTANDINGSOes { get; set; }
        public virtual DbSet<OUTSTANDINGWO> OUTSTANDINGWOes { get; set; }
        public virtual DbSet<V_ACCGRN> V_ACCGRN { get; set; }
        public virtual DbSet<V_COMPANY> V_COMPANY { get; set; }
        public virtual DbSet<V_GRADEINVENTORY> V_GRADEINVENTORY { get; set; }
        public virtual DbSet<V_INVENTORY> V_INVENTORY { get; set; }
        public virtual DbSet<V_INVENTORYITEMS> V_INVENTORYITEMS { get; set; }
        public virtual DbSet<V_IQCDTLITEM> V_IQCDTLITEM { get; set; }
        public virtual DbSet<V_MIDTL> V_MIDTL { get; set; }
        public virtual DbSet<V_PAYEE> V_PAYEE { get; set; }
        public virtual DbSet<V_PO_HISTORY> V_PO_HISTORY { get; set; }
        public virtual DbSet<V_PR_HISTORY> V_PR_HISTORY { get; set; }
        public virtual DbSet<V_QCDTLITEM> V_QCDTLITEM { get; set; }
        public virtual DbSet<V_QCWO> V_QCWO { get; set; }
        public virtual DbSet<V_QUERYSEQNUM> V_QUERYSEQNUM { get; set; }
        public virtual DbSet<V_SINV_HISTORY> V_SINV_HISTORY { get; set; }
        public virtual DbSet<V_SINVDTL> V_SINVDTL { get; set; }
        public virtual DbSet<V_SINVDTL2> V_SINVDTL2 { get; set; }
        public virtual DbSet<V_SINVSCAN_HISTORY> V_SINVSCAN_HISTORY { get; set; }
        public virtual DbSet<V_SO_HISTORY> V_SO_HISTORY { get; set; }
        public virtual DbSet<V_STOCKADJUST> V_STOCKADJUST { get; set; }
        public virtual DbSet<V_STOCKADJUSTDTL> V_STOCKADJUSTDTL { get; set; }
        public virtual DbSet<V_UNSETGRNFORPI> V_UNSETGRNFORPI { get; set; }
        public virtual DbSet<V_UNSETGRNFORPI_BAK> V_UNSETGRNFORPI_BAK { get; set; }
        public virtual DbSet<V_UNSETSINVFORINVOICE> V_UNSETSINVFORINVOICE { get; set; }
        public virtual DbSet<V_WAFERINVENTORY> V_WAFERINVENTORY { get; set; }
        public virtual DbSet<V_WIP> V_WIP { get; set; }
        public virtual DbSet<V_WIP_HISTORY> V_WIP_HISTORY { get; set; }
        public virtual DbSet<V_WIPDTL> V_WIPDTL { get; set; }
        public virtual DbSet<V_WIPSCAN_HISTORY> V_WIPSCAN_HISTORY { get; set; }
    
        [DbFunction("swerpEntities", "F_SPLITSTR")]
        public virtual IQueryable<F_SPLITSTR_Result> F_SPLITSTR(string s, string sPLIT)
        {
            var sParameter = s != null ?
                new ObjectParameter("S", s) :
                new ObjectParameter("S", typeof(string));
    
            var sPLITParameter = sPLIT != null ?
                new ObjectParameter("SPLIT", sPLIT) :
                new ObjectParameter("SPLIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_SPLITSTR_Result>("[swerpEntities].[F_SPLITSTR](@S, @SPLIT)", sParameter, sPLITParameter);
        }
    
        [DbFunction("swerpEntities", "FN_GETDEPT")]
        public virtual IQueryable<FN_GETDEPT_Result> FN_GETDEPT(string dEPTID)
        {
            var dEPTIDParameter = dEPTID != null ?
                new ObjectParameter("DEPTID", dEPTID) :
                new ObjectParameter("DEPTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_GETDEPT_Result>("[swerpEntities].[FN_GETDEPT](@DEPTID)", dEPTIDParameter);
        }
    
        [DbFunction("swerpEntities", "FN_GETDEPTBYUSER")]
        public virtual IQueryable<FN_GETDEPTBYUSER_Result> FN_GETDEPTBYUSER(string uID)
        {
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_GETDEPTBYUSER_Result>("[swerpEntities].[FN_GETDEPTBYUSER](@UID)", uIDParameter);
        }
    
        [DbFunction("swerpEntities", "FN_GETSALEPERSON")]
        public virtual IQueryable<FN_GETSALEPERSON_Result> FN_GETSALEPERSON(string uID)
        {
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_GETSALEPERSON_Result>("[swerpEntities].[FN_GETSALEPERSON](@UID)", uIDParameter);
        }
    
        [DbFunction("swerpEntities", "FN_ITEMTYPES")]
        public virtual IQueryable<FN_ITEMTYPES_Result> FN_ITEMTYPES(string cODE)
        {
            var cODEParameter = cODE != null ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_ITEMTYPES_Result>("[swerpEntities].[FN_ITEMTYPES](@CODE)", cODEParameter);
        }
    }
}
