//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPARVALUE
    {
        public string PARID { get; set; }
        public string VALUEID { get; set; }
        public string NAME { get; set; }
        public decimal VALUE { get; set; }
        public string REMARK { get; set; }
        public int ORD { get; set; }
        public string CREATEDUSER { get; set; }
        public System.DateTime CREATEDSTAMP { get; set; }
        public string UPDATEDUSER { get; set; }
        public Nullable<System.DateTime> UPDATEDSTAMP { get; set; }
    }
}
