//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNSCWA
    {
        public string WONUM { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string PROLINEID { get; set; }
        public Nullable<System.DateTime> WODATE { get; set; }
        public Nullable<System.DateTime> DELIVEYDATE { get; set; }
        public Nullable<decimal> WOQTY { get; set; }
        public Nullable<decimal> SCHEDQTY { get; set; }
        public Nullable<decimal> WIPQTY { get; set; }
        public Nullable<decimal> NONESCHEQTY { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<System.DateTime> PRESCHDATE { get; set; }
        public Nullable<System.DateTime> PLANBEGDATE { get; set; }
        public Nullable<int> UNLIMITED { get; set; }
        public Nullable<int> SELECTED { get; set; }
    }
}
