//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class URPTAB
    {
        public int RPTID { get; set; }
        public string RPTNAME { get; set; }
        public int TYPEID { get; set; }
        public string DICTID { get; set; }
        public int URIGHT { get; set; }
        public int ISALLOWED { get; set; }
    }
}
