//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class URPTAC
    {
        public int RPTID { get; set; }
        public int PARAMID { get; set; }
        public string LEFTSYMBOL { get; set; }
        public int DICTFIELD { get; set; }
        public string FIELDEXP { get; set; }
        public string DEFAULTVALUE { get; set; }
        public string EXPCON { get; set; }
        public string RIGHTSYMBOL { get; set; }
        public Nullable<int> ISREADONLY { get; set; }
    }
}
