//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string UID { get; set; }
        public string NAME { get; set; }
        public string PWD { get; set; }
        public string DEPT { get; set; }
        public string DESCR { get; set; }
        public string EMAIL { get; set; }
        public short ISROLE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATESTAMP { get; set; }
        public string UPDATEUSER { get; set; }
        public short STATUS { get; set; }
        public Nullable<int> CHANGEDPWD { get; set; }
        public Nullable<int> INTERNETACCESS { get; set; }
    }
}
