//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ACCGRN
    {
        public string GRNNUM { get; set; }
        public string PONUM { get; set; }
        public string POLOT { get; set; }
        public string ITEMNUM { get; set; }
        public string ITEMDESCR { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public string LOCID { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    }
}
