//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVENTORYITEMS
    {
        public string ITEMNUM { get; set; }
        public string LOCID { get; set; }
        public string REFNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> MFGDATE { get; set; }
        public Nullable<int> GUAPERIOD { get; set; }
        public string LABELID { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATESTAMP { get; set; }
        public string ITEMDESCR { get; set; }
        public string ITEMDESCRENG { get; set; }
        public string SPEC { get; set; }
        public string SPECCHN { get; set; }
        public string SPECENG { get; set; }
        public string DRAWNUM { get; set; }
        public string ECNNUM { get; set; }
        public string ITEMSUOM { get; set; }
        public int LEADTIME { get; set; }
        public decimal SAFETYSTOCK { get; set; }
        public decimal COST { get; set; }
        public decimal UPRICE { get; set; }
        public string ITEMGRP { get; set; }
        public string ITEMTYPE { get; set; }
        public string BRAND { get; set; }
        public string SRCTYPE { get; set; }
        public decimal MAXORDQTY { get; set; }
        public decimal MINORDQTY { get; set; }
        public decimal FIXORDQTY { get; set; }
        public decimal ECONLOTSIZE { get; set; }
        public decimal REORDQTY { get; set; }
        public string BATCHPRINC { get; set; }
        public string ORDPOLICY { get; set; }
        public string ABC { get; set; }
        public decimal YIELD { get; set; }
        public string INSPECGRADE { get; set; }
        public int SAMPLES { get; set; }
        public string INSPECDESCR { get; set; }
        public string INSPECLEVEL { get; set; }
        public string SAMPLESSTD { get; set; }
        public string AQL { get; set; }
        public decimal WIDTH { get; set; }
        public decimal HEIGHT { get; set; }
        public decimal LENGTH { get; set; }
        public decimal GROSSWEIGHT { get; set; }
        public decimal NETWEIGHT { get; set; }
        public int ITEMGUAPERIOD { get; set; }
    }
}
