//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVENTORY
    {
        public string ITEMNUM { get; set; }
        public string LOCID { get; set; }
        public string REFNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> MFGDATE { get; set; }
        public Nullable<int> GUAPERIOD { get; set; }
        public string LABELID { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATESTAMP { get; set; }
        public string ITEMDESCR { get; set; }
        public string SPEC { get; set; }
        public string ITEMGRP { get; set; }
        public string ITEMTYPE { get; set; }
        public string WONUM { get; set; }
        public string REMARK { get; set; }
        public string WAREHOUSEDESCR { get; set; }
    }
}
