//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IQCDTLITEM
    {
        public string IQCNUM { get; set; }
        public int SEQNUM { get; set; }
        public string QCMETHOD { get; set; }
        public string QCITEM { get; set; }
        public string QCUNIT { get; set; }
        public Nullable<decimal> LOWERLIMITQTY { get; set; }
        public Nullable<decimal> UPPERLIMITQTY { get; set; }
        public Nullable<decimal> TARGETQTY { get; set; }
        public Nullable<decimal> PASSQTY { get; set; }
        public Nullable<decimal> SAMPLEQTY { get; set; }
        public Nullable<decimal> SAMPLEPASSQTY { get; set; }
        public Nullable<int> RESULT { get; set; }
        public string REMARK { get; set; }
        public string CODE { get; set; }
        public string DESCR { get; set; }
        public string ANALYMETHOD { get; set; }
        public string INSPBASIS { get; set; }
        public string QCITEMETHOD { get; set; }
        public string INSPTOOL { get; set; }
        public string SAMPSTD { get; set; }
        public string UOM { get; set; }
        public Nullable<int> CRITICALCHK { get; set; }
        public string DEFECTGRADE { get; set; }
        public Nullable<decimal> DEFECTQTY { get; set; }
    }
}
