//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MIDTL
    {
        public decimal QTY { get; set; }
        public string ITEMNUM { get; set; }
        public string WONUM { get; set; }
        public System.DateTime MIDATE { get; set; }
        public string MITYPE { get; set; }
        public string MINUM { get; set; }
        public string PART { get; set; }
        public decimal PARTQTY { get; set; }
        public string UOM { get; set; }
        public string REMARK { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<decimal> ISSQTY { get; set; }
        public string ITEMDESCR { get; set; }
        public string MITYPEDESCR { get; set; }
    }
}
