//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PAYEE
    {
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string NAME2 { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string CURR { get; set; }
        public string REGION { get; set; }
    }
}
