//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PO_HISTORY
    {
        public string PONUM { get; set; }
        public string POTYPE { get; set; }
        public string REV { get; set; }
        public Nullable<System.DateTime> IDATE { get; set; }
        public string VENID { get; set; }
        public string CURR { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string SHIPTO { get; set; }
        public string SHIPMARK { get; set; }
        public string VIA { get; set; }
        public string REMARK { get; set; }
        public string BUYER { get; set; }
        public string PROJECT { get; set; }
        public string VENITEMNUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public Nullable<System.DateTime> RECVDATE { get; set; }
        public Nullable<decimal> UPRICE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string UOM { get; set; }
        public string PRNUM { get; set; }
        public string DESCR { get; set; }
        public string VENNAME { get; set; }
        public string PAYMETHODDESCR { get; set; }
        public string BUYERDESCR { get; set; }
        public string TRADETERMDESCR { get; set; }
        public string ITEMDESCR { get; set; }
        public Nullable<decimal> EXQTY { get; set; }
        public string EXUOM { get; set; }
        public string PODTLREMARK { get; set; }
        public Nullable<decimal> EXGRNQTY { get; set; }
        public Nullable<decimal> EXREJECTQTY { get; set; }
    }
}
