//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SINVSCAN_HISTORY
    {
        public string SINUM { get; set; }
        public string CUSID { get; set; }
        public System.DateTime IDATE { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public decimal TAXRATE { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string SHIPTO { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string SHIPVIA { get; set; }
        public Nullable<decimal> INSURE { get; set; }
        public Nullable<decimal> HANDLE { get; set; }
        public Nullable<decimal> DELIVERYCHRG { get; set; }
        public Nullable<decimal> MISCHRG { get; set; }
        public string MISCHRGTIT { get; set; }
        public string MISCACC { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> POST { get; set; }
        public string SEQNUM { get; set; }
        public string SONUM { get; set; }
        public string ITEMNUM { get; set; }
        public decimal QTY { get; set; }
        public string SOLOT { get; set; }
        public string LOCID { get; set; }
        public string REFNUM { get; set; }
        public string LOT { get; set; }
        public string LABELID { get; set; }
        public string TRADETERMDESCR { get; set; }
        public string PAYTERMDESCR { get; set; }
        public string ITEMDESCR { get; set; }
        public string CURRDESCR { get; set; }
        public System.DateTime SHIPDATE { get; set; }
        public string PAYMTDESCR { get; set; }
        public string CUSNAME { get; set; }
        public decimal SOQTY { get; set; }
        public string PONUM { get; set; }
        public decimal SINVDTL2QTY { get; set; }
        public decimal SINVDTLQTY { get; set; }
    }
}
