//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SO_HISTORY
    {
        public string SONUM { get; set; }
        public string SOTYPE { get; set; }
        public string CUSID { get; set; }
        public System.DateTime IDATE { get; set; }
        public string REV { get; set; }
        public string PONUM { get; set; }
        public string CURR { get; set; }
        public decimal RATE { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string SHIPMARK { get; set; }
        public string VIA { get; set; }
        public string REMARK { get; set; }
        public string SOLDTO { get; set; }
        public string SHIPTO { get; set; }
        public string BILLTO { get; set; }
        public string SALESREP { get; set; }
        public string SALESREGION { get; set; }
        public string PROJECT { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public string CUSITEMNUM { get; set; }
        public System.DateTime SHIPDATE { get; set; }
        public Nullable<System.DateTime> PLANDATE { get; set; }
        public decimal UPRICE { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CUSNAME { get; set; }
        public string SOTYPEDESCR { get; set; }
        public string ITEMDESCR { get; set; }
    }
}
