//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WAFERINVENTORY
    {
        public string ITEMNUM { get; set; }
        public string LOCID { get; set; }
        public string REFNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> MFGDATE { get; set; }
        public Nullable<int> GUAPERIOD { get; set; }
        public string LABELID { get; set; }
        public System.DateTime UPDATESTAMP { get; set; }
        public string STATUS { get; set; }
        public string BIN { get; set; }
        public string WAFER { get; set; }
        public Nullable<decimal> DICEHEIGHT { get; set; }
        public Nullable<decimal> LOPCOV { get; set; }
        public string VFAID { get; set; }
        public Nullable<decimal> VFAMIN { get; set; }
        public Nullable<decimal> VFAMAX { get; set; }
        public Nullable<decimal> VFAAVG { get; set; }
        public Nullable<decimal> VFASTD { get; set; }
        public string WDAID { get; set; }
        public Nullable<decimal> WDAMIN { get; set; }
        public Nullable<decimal> WDAMAX { get; set; }
        public Nullable<decimal> WDAAVG { get; set; }
        public Nullable<decimal> WDASTD { get; set; }
        public Nullable<decimal> WAVELENGTHSIGMA { get; set; }
        public string IVAID { get; set; }
        public Nullable<decimal> IVAMIN { get; set; }
        public Nullable<decimal> IVAMAX { get; set; }
        public Nullable<decimal> IVAAVG { get; set; }
        public Nullable<decimal> IVASTD { get; set; }
        public string ITEMGRP { get; set; }
        public string ITEMTYPE { get; set; }
        public string ITEMDESCR { get; set; }
        public string SPEC { get; set; }
        public string VENID { get; set; }
        public string PONUM { get; set; }
    }
}
