//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WIP
    {
        public string WIPNUM { get; set; }
        public System.DateTime WIPDATE { get; set; }
        public Nullable<int> COMPLETED { get; set; }
        public string WIPTYPE { get; set; }
        public string LOCID { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public string LABELID { get; set; }
        public Nullable<System.DateTime> MFGDATE { get; set; }
        public string REMARK { get; set; }
        public string TYPE { get; set; }
    }
}
