//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        public string VENID { get; set; }
        public string VENNAME { get; set; }
        public string CURR { get; set; }
        public string PAYTERM { get; set; }
        public string PAYMETHOD { get; set; }
        public string TRADETERM { get; set; }
        public string SALESCONTACT { get; set; }
        public string SALESMAIL { get; set; }
        public string SALESTEL { get; set; }
        public string SALESFAX { get; set; }
        public string SALESADDR { get; set; }
        public string ACCCONTACT { get; set; }
        public string ACCMAIL { get; set; }
        public string ACCTEL { get; set; }
        public string ACCFAX { get; set; }
        public string ACCADDR { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string TMPAYACC { get; set; }
        public string PURACC { get; set; }
        public string PAYACC { get; set; }
        public string APACC { get; set; }
        public string OPACC { get; set; }
        public string WEBSITE { get; set; }
        public string SHORTNAME { get; set; }
        public string INDUSTRY { get; set; }
        public string MOBILE { get; set; }
        public string ZIP { get; set; }
        public string BANKACC { get; set; }
        public string BANK { get; set; }
        public string TMTAXACC { get; set; }
        public string RANKTYPE { get; set; }
        public Nullable<int> ISDENY { get; set; }
        public string SCACC { get; set; }
        public string VENNAME2 { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> CREATEDSTAMP { get; set; }
        public string REMARKS { get; set; }
    
        public virtual BUYER BUYER { get; set; }
        public virtual INVTYPE INVTYPE { get; set; }
        public virtual VENTYPE VENTYPE { get; set; }
    }
}
