//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHR
    {
        public string VID { get; set; }
        public string VTYPE { get; set; }
        public System.DateTime VDATE { get; set; }
        public int FYEAR { get; set; }
        public int FPERIOD { get; set; }
        public int VNUM { get; set; }
        public string VREFINFO { get; set; }
        public string VBASETYPE { get; set; }
        public string VBASENUM { get; set; }
        public Nullable<System.DateTime> VBASEDATE { get; set; }
        public Nullable<int> ATTACHS { get; set; }
        public string PRJCODE { get; set; }
        public string DEPTID { get; set; }
        public string PAYEE { get; set; }
        public string PAYEETYPE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string APPROVEDBY { get; set; }
        public Nullable<System.DateTime> APPROVED { get; set; }
    }
}
