//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUENY
    {
        public string VID { get; set; }
        public int LINEID { get; set; }
        public string ACCNUM { get; set; }
        public string LINEMEMO { get; set; }
        public decimal ORIAMT { get; set; }
        public decimal RATE { get; set; }
        public string CURRCODE { get; set; }
        public decimal DEBIT { get; set; }
        public decimal CREDIT { get; set; }
    }
}
