//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAFERDATA
    {
        public int ID { get; set; }
        public System.DateTime IMPDATE { get; set; }
        public string REMARK { get; set; }
        public string LABELID { get; set; }
        public string BIN { get; set; }
        public string WAFER { get; set; }
        public Nullable<decimal> DICEHEIGHT { get; set; }
        public Nullable<decimal> LOPCOV { get; set; }
        public string VFAID { get; set; }
        public Nullable<decimal> VFAMIN { get; set; }
        public Nullable<decimal> VFAMAX { get; set; }
        public Nullable<decimal> VFAAVG { get; set; }
        public Nullable<decimal> VFASTD { get; set; }
        public string WDAID { get; set; }
        public Nullable<decimal> WDAMIN { get; set; }
        public Nullable<decimal> WDAMAX { get; set; }
        public Nullable<decimal> WDAAVG { get; set; }
        public Nullable<decimal> WDASTD { get; set; }
        public Nullable<decimal> WAVELENGTHSIGMA { get; set; }
        public string IVAID { get; set; }
        public Nullable<decimal> IVAMIN { get; set; }
        public Nullable<decimal> IVAMAX { get; set; }
        public Nullable<decimal> IVAAVG { get; set; }
        public Nullable<decimal> IVASTD { get; set; }
        public string VFBID { get; set; }
        public string IVBID { get; set; }
        public string WDBID { get; set; }
        public Nullable<decimal> VFBMIN { get; set; }
        public Nullable<decimal> VFBMAX { get; set; }
        public Nullable<decimal> IVBMIN { get; set; }
        public Nullable<decimal> IVBMAX { get; set; }
        public Nullable<decimal> WDBMIN { get; set; }
        public Nullable<decimal> WDBMAX { get; set; }
        public string VFCID { get; set; }
        public string IVCID { get; set; }
        public string WDCID { get; set; }
        public Nullable<decimal> VFCMIN { get; set; }
        public Nullable<decimal> VFCMAX { get; set; }
        public Nullable<decimal> IVCMIN { get; set; }
        public Nullable<decimal> IVCMAX { get; set; }
        public Nullable<decimal> WDCMIN { get; set; }
        public Nullable<decimal> WDCMAX { get; set; }
        public string POS { get; set; }
        public Nullable<decimal> POS1X { get; set; }
        public Nullable<decimal> POS1Y { get; set; }
        public Nullable<decimal> POS2X { get; set; }
        public Nullable<decimal> POS2Y { get; set; }
        public Nullable<decimal> POS3X { get; set; }
        public Nullable<decimal> POS3Y { get; set; }
        public Nullable<decimal> POS4X { get; set; }
        public Nullable<decimal> POS4Y { get; set; }
    }
}
