//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        public string CODE { get; set; }
        public string DESCR { get; set; }
        public string MASTER { get; set; }
        public Nullable<int> ADDINPR { get; set; }
        public Nullable<int> ISBACKFLUSH { get; set; }
        public Nullable<int> ADDINSI { get; set; }
        public Nullable<int> ISFGWH { get; set; }
        public Nullable<int> ISFGSCPWH { get; set; }
        public Nullable<int> ISMATWH { get; set; }
        public Nullable<int> ISFGWH2 { get; set; }
        public Nullable<int> ISFGWH3 { get; set; }
        public Nullable<int> ISMATWH2 { get; set; }
        public Nullable<int> STOCKOUTREF { get; set; }
        public Nullable<int> SAFETYSTOCKWARNING { get; set; }
    }
}
