//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIPDTL
    {
        public string WIPNUM { get; set; }
        public string WONUM { get; set; }
        public string ITEMNUM { get; set; }
        public string LOT { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }
        public string LABELID { get; set; }
        public Nullable<System.DateTime> MFGDATE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public int GUAPERIOD { get; set; }
        public int ISMATCHED { get; set; }
        public string CUSTOMLABELID { get; set; }
    }
}
